- .github/workflows/code-scan.yml
- .github/workflows/scripts/codeScan/hadolint.sh
validation 
add hadolint scan in CI
CI
No
> add hadolint scan in CI

- .github/workflows/scripts/codeScan/trellix.sh
- .github/workflows/trellix.yml
validation 
enable trellix for virus scan
CI
trellix
> enable trellix for virus scan

- .github/workflows/scripts/codeScan/bandit.sh
- .github/workflows/scripts/codeScan/trellix.sh
validation 
update code scan config
CI
No
> update code scan

- .github/workflows/scripts/codeScan/trellix.sh
- .github/workflows/trellix.yml
validation 
update trellix scan
> update trellix scan

- comps/reranks/README.md
- comps/reranks/docker/docker_compose_reranking.yaml
- comps/reranks/requirements.txt
bug fix
Add needed requirements and environment variables for reranking microservice.
Local tested on SPR
Add requirements.txt.
> Fix variables issues of Reranking Microservice

- comps/asr/Dockerfile
- comps/asr/README.md
- comps/asr/requirements.txt
- comps/cores/telemetry/requirements.txt
- comps/tts/Dockerfile
- comps/tts/README.md
- comps/tts/requirements.txt
doc
add docker and readme for asr/tts microservices
None
None
> add docker and readme for asr/tts microservices

- comps/embeddings/README.md
- comps/embeddings/langchain/docker/docker_compose_embedding.yaml
- comps/embeddings/langchain/requirements.txt
- comps/llms/README.md
- comps/llms/langchain/llm_tgi.py
bug fix
Fix issues of Embedding and LLM Microservice, including python file, requirements, yaml and README.
modify requirements.txt
> Fix issues of Embedding and LLM Microservice

- comps/asr/README.md
- comps/embeddings/README.md
- comps/embeddings/langchain/docker/docker_compose_embedding.yaml
- comps/guardrails/README.md
- comps/guardrails/langchain/docker/docker_compose_guardrails.yaml
- comps/llms/README.md
- comps/llms/langchain/docker/docker_compose_llm.yaml
- comps/reranks/README.md
- comps/reranks/docker/docker_compose_reranking.yaml
- comps/retrievers/README.md
- comps/retrievers/langchain/docker/docker_compose_retriever.yaml
- comps/tts/README.md
feature
Rename docker image name
Just change docker image name
None
> Rename docker image name

- .github/license_template.txt
- .github/workflows/code-scan.yml
- .github/workflows/embeddings-comp-test.yml
- .github/workflows/llms-comp-test.yml
- .github/workflows/mega-test.yaml
- .github/workflows/trellix.yml
- comps/vectorstores/langchain/qdrant/__init__.py
- setup.py
documentation 
update license template
pre-commit CI bot
No
> update license template

- comps/asr/requirements.txt
- comps/embeddings/README.md
- comps/embeddings/langchain/requirements.txt
- comps/guardrails/requirements.txt
- comps/llms/langchain/docker/Dockerfile
- comps/llms/requirements.txt
- comps/retrievers/requirements.txt
- comps/tts/requirements.txt
bug fix
Fix requirement issue
Add opentelemetry in requirements.txt for each microservices.
Add opentelemetry in requirements.txt
> Fix requirement issue of Microservices

- comps/cores/telemetry/collector-config.yaml
- comps/cores/telemetry/opea_telemetry.py
- comps/llms/langchain/docker/Dockerfile
- comps/llms/langchain/llm_tgi.py
- comps/tts/Dockerfile
- comps/tts/tts.py
feature & bug fix
This is for building AudioQnA
LLM generated Long text need to be batched (SpeechT5 has 600 length limit) and the logics are added. (refer to https://github.com/huggingface/transformers/pull/25943)
Input/Output types bug fix.
Telemetry req/port fix.
local test
None
> Add auto batched generation TTS and fix AudioQna flow

- comps/retrievers/langchain/retriever_redis.py
bug fix
fix the relative import
local test
no
> fix the relative import.

- comps/cores/mega/constants.py
- comps/cores/mega/orchestrator.py
- comps/cores/proto/api_protocol.py
feature
Add megaservice gateway
Local test, megaservice pipeline test.
None
> Add megaservice gateway

- comps/asr/requirements.txt
- comps/cores/mega/orchestrator.py
- comps/embeddings/langchain/requirements.txt
- comps/guardrails/requirements.txt
- comps/llms/requirements.txt
- comps/reranks/requirements.txt
- comps/retrievers/langchain/docker/Dockerfile
- comps/retrievers/langchain/run.sh
- comps/retrievers/requirements.txt
- comps/tts/requirements.txt
feature
Ingest data automatically in Retriever Microservice when creating docker container.
Fix package import issue.
Add package requirements.
Update requirements.txt of microservices.
> Ingest data automatically in Retriever Microservice

- comps/llms/README.md
- comps/llms/langchain/docker/docker_compose_llm.yaml
- comps/llms/langchain/llm_tgi.py
feature
Support LLM Microservice with Streaming Response
Add `/v1/chat/completions_stream` api for streaming llm.
Local tested on SPR
None
> Support LLM Microservice with Streaming Response

- comps/reranks/langchain/docker/Dockerfile
bug fix
Modify workdir of Rerank
how to reproduce the test (including hardware information)
any library dependency introduced or removed
> Modify workdir of Rerank

- comps/dataprep/langchain/qdrant/prepare_doc_qdrant.py
- comps/dataprep/langchain/redis/prepare_doc_redis.py
- comps/embeddings/langchain/embedding_tei_gaudi.py
- comps/embeddings/langchain/local_embedding.py
- comps/guardrails/langchain/guardrails_tgi_gaudi.py
- comps/llms/langchain/llm_tgi.py
- comps/reranks/langchain/local_reranking.py
- comps/reranks/langchain/reranking_tei_xeon.py
- comps/retrievers/langchain/retriever_redis.py
feature
add telemery for all services
Local test
None
> Add telemery for all services

- comps/cores/mega/orchestrator_with_yaml.py
- tests/cores/mega/test_service_orchestrator.py
- tests/cores/mega/test_service_orchestrator_with_gateway.py
- tests/cores/mega/test_service_orchestrator_with_yaml.py
bug fix
async test needs `unittest.IsolatedAsyncioTestCase`
UT
None
> Fix async test

- comps/cores/mega/http_service.py
feature
Enable cors by default
Local test
None
> Enable cors by default

- comps/dataprep/langchain/qdrant/README.md
- comps/dataprep/langchain/qdrant/docker/Dockerfile
- comps/dataprep/langchain/qdrant/docker/docker-compose-dataprep-qdrant.yaml
- comps/dataprep/langchain/qdrant/prepare_doc_qdrant.py
- comps/dataprep/langchain/qdrant/requirements.txt
- comps/dataprep/langchain/redis/README.md
- comps/dataprep/langchain/redis/docker/Dockerfile
- comps/dataprep/langchain/redis/docker/docker-compose-dataprep-redis.yaml
- comps/dataprep/langchain/redis/requirements.txt
bug fix, documentation
Fix dockers of dataprep and refined README.
follow readme
no library dependency introduced or removed
> Fix dockers of dataprep and refined README

- comps/__init__.py
- comps/cores/mega/gateway.py
Add CodeGen and CodeTrans gateway
New feature
None
Local test.
> Add CodeGen and CodeTrans gateway

- comps/cores/telemetry/opea_telemetry.py
Fix telemetry endpoint with an env variable
n/a
None
UT
> Fix telemetry endpoint

- comps/cores/mega/gateway.py
Update CodeTrans Prompt.
Use String format to replace `langchain`.
n/a
None
> Update CodeTrans Prompt

- .github/workflows/container-build.yaml
- .github/workflows/docker/docker-compose.yaml
Add Action to build all containers, similar to https://github.com/opea-project/GenAIExamples/pull/166.
n/a
> Add Container Build Action

- .github/workflows/container-build.yaml
- .github/workflows/docker/docker-compose.yaml
Remove the label in docker image tag, for internal ci to pull the latest docker image. 
n/a
NA
Action
> remove the label in docker image tag

- comps/llms/text-generation/tgi/llm.py
Add Timeout for LLM Microservice
n/a
None
> Add Timeout for LLM Microservice

- comps/dataprep/redis/README.md
- comps/dataprep/redis/docker/docker-compose-dataprep-redis.yaml
- comps/embeddings/README.md
- comps/embeddings/langchain/docker/docker_compose_embedding.yaml
- comps/llms/README.md
- comps/reranks/README.md
- comps/reranks/langchain/docker/docker_compose_reranking.yaml
- comps/retrievers/README.md
- comps/retrievers/langchain/docker/docker_compose_retriever.yaml
Format opea docker images name
align with https://github.com/opea-project/GenAIExamples/pull/186
> Format opea docker images name

- CONTRIBUTING.md
- README.md
- comps/dataprep/README.md
- comps/dataprep/qdrant/README.md
- comps/dataprep/redis/README.md
fix grammar error
fix grammar error
> fix grammar error

- comps/retrievers/README.md
- tests/test_retrievers.sh
fix curl command format in readme and test
`n/a`.
None
test_retrievers.sh
> fix curl command format in readme and test

- LEGAL_INFORMATION.md
- README.md
- SECURITY.md
- comps/version.py
- third-party-programs.txt
- bump release version into v0.6  
- update security files
n/a
no
no
> bump release version into v0.6

- comps/cores/mega/gateway.py
`get_all_final_outputs` requires a result_dict passed
n/a
None
None
> fix gateway

- .github/workflows/microservice-test.yml
- tests/test_llms.sh
Fix the get test matrix issue when the changed file detect is empty in microservice test workflow. 
https://github.com/opea-project/GenAIComps/pull/138
No
CI
> fix the get test matrix issue

- comps/__init__.py
- comps/cores/mega/constants.py
- comps/cores/proto/docarray.py
- comps/ragas/tgi/Dockerfile
- comps/ragas/tgi/__init__.py
- comps/ragas/tgi/build_docker.sh
- comps/ragas/tgi/docker_compose_llm.yaml
- comps/ragas/tgi/llm.py
- comps/ragas/tgi/requirements.txt
Build a new microservice for RAGAS;
accept input type:  [questions], [answer], [docs],[ground_truth]
it will return the evaluation scores from four perspectives: answer_relevancy, context_precision, context_recall, faithfulness
> Enable RAGAS to evaluate the rag performance

- comps/dataprep/redis/langchain/docker/Dockerfile
Fix dataprep microservice path issue
`n/a`
- [ x ] Bug fix (non-breaking change which fixes an issue)
None
Local test.
> Fix dataprep microservice path issue

- .github/workflows/megaservice-test.yml
- .github/workflows/scripts/test_ut.sh
- codecov.yml
> Add codecov

- comps/dataprep/redis/README.md
Update Dataprep Microservice README
n/a
None
None
> Update Dataprep Microservice README

- comps/dataprep/utils.py
Fix dataprep timeout issue
`n/a`
- [ x ] Bug fix (non-breaking change which fixes an issue)
None
Local test.
> Fix dataprep timeout issue

- comps/embeddings/langchain-mosec/README.md
- comps/embeddings/langchain-mosec/__init__.py
- comps/embeddings/langchain-mosec/docker/Dockerfile
- comps/embeddings/langchain-mosec/docker/docker_compose_embedding.yaml
- comps/embeddings/langchain-mosec/embedding_mosec.py
- comps/embeddings/langchain-mosec/mosec-docker/Dockerfile
- comps/embeddings/langchain-mosec/mosec-docker/README.md
- comps/embeddings/langchain-mosec/mosec-docker/server-ipex.py
- comps/embeddings/langchain-mosec/mosec-docker/test-embedding.py
- comps/embeddings/langchain-mosec/requirements.txt
- tests/test_embeddings_langchain-mosec.sh
Add a new embedding MosecEmbedding.
n/a
- [ *] New feature (non-breaking change which adds new functionality)
Mosec
langchain
openai
Tested all steps from the README.md in comps/embeddings/langchain-mosec.
> Add a new embedding MosecEmbedding

- .github/workflows/microservice-test.yml
expand timeout for microservice test
https://github.com/opea-project/GenAIComps/actions/runs/9559407896/job/26349738306?pr=181
> expand timeout for microservice test

- .github/workflows/container-build.yml
- .github/workflows/microservice-test.yml
add secrets in ci test
https://github.com/opea-project/GenAIComps/pull/209/ 
> add secrets in ci test

- .github/workflows/megaservice-test.yml
Add E2E test trigger solution for CodeCov
> Add E2E test trigger solution

- .github/workflows/reuse-get-test-matrix.yml
> fix ci corner issue

- comps/dataprep/redis/langchain/docker/Dockerfile
fix install deps in comps/dataprep/redis/langchain/docker/Dockerfile
> fix install deps in comps/dataprep/redis/langchain/docker/Dockerfile

- README.md
add LlamaIndex for readme
`n/a`.
> add LlamaIndex for readme

- comps/llms/text-generation/ollama/llm.py
Fix ChatQnA issues when using Ollama as LLM
n/a
None
None
> Fix ChatQnA issues when using Ollama as LLM

- comps/guardrails/pii_detection/pii/pii_utils.py
Remove sensitive info log
`n/a`.
no
test_guardrails_pii_detection.sh
> Remove sensitive info logs

- comps/version.py
> bump version into v0.7

- comps/llms/text-generation/vllm/README.md
- comps/llms/text-generation/vllm/launch_vllm_service.sh
Update vllm readme for better instruction
n/a.
> refine vllm instruction

- comps/guardrails/README.md
- comps/guardrails/langchain/guardrails_tgi_gaudi.py
Fix Llama-Guard-2 issue
`n/a`
- [  x ] Bug fix (non-breaking change which fixes an issue)
None.
Local test and pre-CI test
> Fix Llama-Guard-2 issue

- comps/cores/mega/micro_service.py
Support https for microservice
n/a`
- [ x ] New feature (non-breaking change which adds new functionality)
None
Local test and pre-CI test
> Support https for microservice

- comps/dataprep/milvus/prepare_doc_milvus.py
- comps/dataprep/pgvector/langchain/prepare_doc_pgvector.py
- comps/dataprep/pinecone/prepare_doc_pinecone.py
- comps/dataprep/qdrant/prepare_doc_qdrant.py
- comps/dataprep/redis/langchain/prepare_doc_redis.py
- comps/dataprep/redis/langchain_ray/prepare_doc_redis_on_ray.py
- comps/dataprep/utils.py
Adding separators for raw text data chunk to keep the semantic completeness, it's very necessary to make the raw text data chunk meaningful.
`n/a`.
`n/a`.
I have tested the redis and milvus
> Enhance the dataprep microservice by adding separators.

- comps/reranks/fastrag/docker/Dockerfile
- tests/test_reranks_fastrag.sh
fix requirements install issue  
> fix requirements install issue for reranks/fastrag

- comps/cores/mega/micro_service.py
Remove unused replicas parameter
`n/a`
- [ x ] Bug fix (non-breaking change which fixes an issue)
None
Local test and pre-CI test
> Remove unused replicas parameter

- comps/llms/text-generation/vllm/README.md
Fix syntax error in command 
n/a
- [x ] Bug fix (non-breaking change which fixes an issue)
> doc: add missing ' in README.md codeblock

- comps/version.py
> bump version into v0.8

- comps/embeddings/langchain-mosec/embedding_mosec.py
- comps/embeddings/langchain-mosec/mosec-docker/README.md
- comps/embeddings/langchain-mosec/mosec-docker/server-ipex.py
- comps/embeddings/langchain-mosec/mosec-docker/test-embedding.py
The PR is used to fix some typos in #387
n/a
n/a
local test pass
> Fix issues in updating embedding & reranking model to bge-large-zh-v1.5

- comps/guardrails/toxicity_detection/toxicity_detection.py
Minor SPDX header update for consistency purpose
None
N/A
> Minor SPDX header update

- .github/workflows/microservice-test.yml
> add secrets for test

- comps/llms/README.md
- comps/llms/text-generation/vllm-ray/README.md
- comps/llms/text-generation/vllm-ray/build_docker_vllmray.sh
- comps/llms/text-generation/vllm-ray/docker_compose_llm.yaml
- comps/llms/text-generation/vllm-ray/launch_vllmray.sh
- comps/llms/text-generation/vllm-ray/requirements.txt
- comps/llms/text-generation/vllm/README.md
- comps/llms/text-generation/vllm/build_docker_vllm.sh
- comps/llms/text-generation/vllm/docker/Dockerfile.hpu
- comps/llms/text-generation/vllm/docker_compose_llm.yaml
- comps/llms/text-generation/vllm/launch_vllm_service.sh
- tests/test_llms_text-generation_vllm-ray.sh
- tests/test_llms_text-generation_vllm.sh
Vllm and vllm-ray fix (add opea for vllm, update setuptools version)
> Vllm and vllm-ray bug fix (add opea for vllm, update setuptools version)

- comps/llms/text-generation/vllm-ray/llm.py
unify llms response to one format (tgi) for ui
currently, vllm/vllm-ray/tgi/ollama/vllm-xft have same response format
> align vllm-ray response format to tgi response format

- .github/workflows/docker/compose/llms-compose.yaml
> build new images for llms

- .github/workflows/_get-test-matrix.yml
- .github/workflows/pr-microservice-test.yml
Update Microservice CI trigger path
https://github.com/opea-project/GenAIComps/pull/445 
In order to trigger the test due to the requirements change. 
> Update Microservice CI trigger path

- comps/asr/whisper/Dockerfile
> whisper: Fix container build failure

- comps/embeddings/langchain-mosec/mosec-docker/Dockerfile
- comps/embeddings/langchain-mosec/mosec-docker/server-ipex.py
Fix embeddings_langchain-mosec issue.
> Fix embeddings_langchain-mosec issue.

- comps/dataprep/pgvector/langchain/requirements.txt
> Address testcase failure

- comps/dataprep/qdrant/README.md
- comps/dataprep/qdrant/config.py
- comps/dataprep/qdrant/docker/Dockerfile
- comps/dataprep/qdrant/docker/docker-compose-dataprep-qdrant.yaml
- comps/dataprep/qdrant/prepare_doc_qdrant.py
- comps/dataprep/qdrant/requirements.txt
- tests/test_dataprep_qdrant_langchain.sh
Fix Dataprep qdrant issues and add Test Script
The CI failed [here](https://github.com/opea-project/GenAIExamples/pull/569) for ChatQnA qdrant.
modified in requirements.txt
Local tested using test script
> Fix Dataprep qdrant issues and add Test Script

- tests/test_llms_text-generation_native.sh
> Modify validate result check.

- .github/workflows/pr-examples-test.yml
add sudo in wf remove
https://github.com/opea-project/GenAIComps/actions/runs/10419593982/job/28857963864?pr=505
> add sudo in wf remove

- comps/cores/mega/micro_service.py
- comps/cores/proto/api_protocol.py
- comps/finetuning/finetuning.py
- comps/finetuning/handlers.py
Add finetuning list job, cancel job, retrieve finetuning job feature.
`n/a`.
test pass.
curl response api.
> Add finetuning list job, cancel job, retrieve finetuning job feature

- .github/workflows/manual-freeze-images.yml
- .github/workflows/scripts/freeze_images.sh
Add freeze docker images workflow
n/a
n/a
n/a
> Freeze base images

- comps/nginx/docker/Dockerfile
- comps/nginx/docker/nginx.conf.template
- comps/nginx/docker/start-nginx.sh
- tests/test_nginx.sh
Refine Nginx component of homepage forwarding.
Add test for Nginx.
n/a
None
Local tested with test script
> Refine Nginx Component

- .github/workflows/docker/compose/tts-compose.yaml
Fix the issue of the built tts image having the wrong name of asr.
`n/a`.
n/a.
> Fix tts image build error

- comps/cores/proto/api_protocol.py
Modify `temperature` from 1.0 to 0.01.
LLM response with irrelevant answers.
None
Local tested.
Response after change:
> Refine parameter in api_protocol.py

- comps/guardrails/toxicity_detection/requirements.txt
- comps/guardrails/toxicity_detection/toxicity_detection.py
Remove 'langsmith' per code review
> Remove 'langsmith' per code review

- comps/dataprep/redis/langchain/prepare_doc_redis.py
Fix /v1/dataprep/get_file error of getting file list from an empty index.
Check index existance before getting data from db.
Refine dataprep logs.
n/a
None
Local tested
> Fix Dataprep Potential Error in get_file

- comps/finetuning/README.md
- comps/finetuning/docker/Dockerfile_hpu
- comps/finetuning/finetuning_service.py
- comps/finetuning/handlers.py
- comps/finetuning/lanuch.sh
- comps/finetuning/llm_on_ray/common/__init__.py
- comps/finetuning/llm_on_ray/common/common.py
- comps/finetuning/llm_on_ray/common/torch_config.py
- comps/finetuning/llm_on_ray/finetune/__init__.py
- comps/finetuning/llm_on_ray/finetune/data_process.py
- comps/finetuning/llm_on_ray/finetune/finetune.py
- comps/finetuning/llm_on_ray/finetune/finetune_config.py
- comps/finetuning/models/llama-2-7b-chat-hf.yaml
- comps/finetuning/models/mistral-7b-v0.1.yaml
- comps/finetuning/requirements.txt
> Add finetuning gaudi

- comps/finetuning/README.md
- comps/finetuning/llm_on_ray/common/__init__.py
- comps/finetuning/llm_on_ray/common/common.py
- comps/finetuning/llm_on_ray/common/logging.py
- comps/finetuning/llm_on_ray/common/torch_config.py
- comps/finetuning/llm_on_ray/finetune/__init__.py
- comps/finetuning/llm_on_ray/finetune/data_process.py
- comps/finetuning/llm_on_ray/finetune/finetune.py
- comps/finetuning/llm_on_ray/finetune/finetune_config.py
> fix license and typo

- comps/asr/Dockerfile
- comps/asr/requirements.txt
- comps/asr/whisper/Dockerfile
- comps/tts/Dockerfile
- comps/tts/requirements.txt
- comps/tts/speecht5/Dockerfile
Update the requirements.txt for tts and asr. 
When we freeze the torch/torchvision issue in rc branch, the torch in habana container will be reinstalled and break the env. So only install the cpu version of torch/torchvision in cpu contianer. 
https://github.com/opea-project/GenAIExamples/actions/runs/10493762658/job/29069015841
> update the requirements.txt for tts and asr

- comps/web_retrievers/langchain/chroma/README.md
Fix searchqna readme. Find a suitable prompt which have a stable answer to reproduce. Also fix some env variables in instructions.
The returned answer should display the correct issue date, the source link, the summary of the top1 web page relevant to the prompt.
n/a
n/a
n/a
> fix searchqna readme

- comps/version.py
> bump version into v1.0

- .github/workflows/pr-microservice-test.yml
> expand CI timeout

- comps/lvms/video-llama/server/requirements.txt
- comps/lvms/video-llama/server/server.py
- tests/test_lvms_video-llama.sh
Fix the security issue in video-llama LVM. 
https://github.com/opea-project/GenAIComps/security/code-scanning/6
https://github.com/opea-project/GenAIComps/security/code-scanning/7
https://github.com/opea-project/GenAIComps/security/code-scanning/8
> BUG FIX: LVM security fix

- .github/workflows/_get-test-matrix.yml
- .github/workflows/pr-examples-test.yml
- .github/workflows/pr-microservice-test.yml
update CI test log achieve when test failed for ChatQnA example. 
When test failed, no artifacts achieved. 
https://github.com/opea-project/GenAIComps/actions/runs/10574283290/job/29402658924?pr=539
> update CI test log achieve

- comps/cores/proto/docarray.py
Fix the conflict definition of ImageDoc, TextImageDoc and SearchedMultimodalDoc. 
Issue mentioned in comment: https://github.com/opea-project/GenAIComps/pull/496#issuecomment-2317686093
This change impact below PR: #496 #539 #575
> BUGFIX: fix SearchedMultimodalDoc in docarray

- .github/workflows/manual-bom-scan.yml
Make the scanning method optional.
> Make the scanning method optional.

- .github/workflows/_comps-workflow.yml
- .github/workflows/docker/compose/agent-compose-cd.yaml
- .github/workflows/docker/compose/asr-compose.yaml
- .github/workflows/docker/compose/chathistory-compose-cd.yaml
- .github/workflows/docker/compose/dataprep-compose-cd.yaml
- .github/workflows/docker/compose/dataprep-compose.yaml
- .github/workflows/docker/compose/embeddings-compose-cd.yaml
- .github/workflows/docker/compose/embeddings-compose.yaml
- .github/workflows/docker/compose/guardrails-compose-cd.yaml
- .github/workflows/docker/compose/guardrails-compose.yaml
- .github/workflows/docker/compose/llms-compose-cd.yaml
- .github/workflows/docker/compose/llms-compose.yaml
- .github/workflows/docker/compose/lvms-compose-cd.yaml
- .github/workflows/docker/compose/nginx-compose-cd.yaml
- .github/workflows/docker/compose/prompt_registry-compose-cd.yaml
- .github/workflows/docker/compose/reranks-compose-cd.yaml
- .github/workflows/docker/compose/reranks-compose.yaml
- .github/workflows/docker/compose/retrievers-compose-cd.yaml
- .github/workflows/docker/compose/retrievers-compose.yaml
- .github/workflows/docker/compose/tts-compose.yaml
- .github/workflows/docker/compose/web_retrievers-compose.yaml
- .github/workflows/manual-image-build.yml
- .github/workflows/push-image-build.yml
- .github/workflows/schedule-image-build.yml
> Change image tag.

- .github/workflows/_get-image-list.yml
- .github/workflows/manual-bom-scan.yml
- .github/workflows/manual-docker-publish.yml
- .github/workflows/manual-docker-scan.yml
image scan and publish cd enhance
> image scan and publish cd enhance

- .github/workflows/_comps-workflow.yml
- .github/workflows/docker/compose/llms-compose-cd.yaml
- .github/workflows/docker/compose/lvms-compose-cd.yaml
> Fix image build fail issue.

- comps/dataprep/utils.py
Add some fixes to allow Chinese web pages injection for ChatQnA example.
To address #587
> Dataprep fetch page fix

- .github/workflows/_comps-workflow.yml
- .github/workflows/docker/compose/llms-compose-cd.yaml
- .github/workflows/docker/compose/lvms-compose-cd.yaml
- .github/workflows/docker/compose/vectorstores-compose-cd.yaml
- comps/dataprep/utils.py
> Add compose file.

- comps/feedback_management/mongo/docker/Dockerfile
Remove vim packages from microservices's Dockerfile to align with all other services.
N/A
- [*] Others (enhancement, documentation, validation, etc.)
N/A
N/A
> feedback_management: Remove 'vim' from Dockerfile

- comps/dataprep/milvus/docker/docker-compose-dataprep-milvus.yaml
- comps/vectorstores/langchain/milvus/docker-compose.yml
To avoid port conflicts change port to others.
> To avoid port conflicts change port to others.

- comps/retrievers/langchain/pgvector/docker/Dockerfile
- comps/retrievers/langchain/pgvector/run.sh
- comps/retrievers/langchain/vdms/docker/Dockerfile
- comps/retrievers/langchain/vdms/run.sh
Clear the unnecessary scripts and `Dockerfile` commands for retriever of `pgvector` and `vdms`
`n/a`.
`n/a`.
I have validated the images building for these 2 retrievers.
> clear some unnecessary scripts and Dockerfile commands.

- comps/cores/mega/orchestrator.py
https://github.com/opea-project/GenAIComps/pull/582 add a limitation for llm parameters setting, it caused the LVM streaming issue.
`n/a`
None
Local test and pre-CI.
> Fix LVM streaming issue

- comps/finetuning/README.md
Added finetuned model deployment tutorial in readme.
`n/a`.
Documentation.
> Added finetuned model deployment tutorial in readme

- comps/intent_detection/langchain/intent_detection.py
- comps/intent_detection/langchain/requirements.txt
- comps/intent_detection/langchain/template.py
- comps/lvms/tgi-llava/requirements.txt
- tests/intent_detection/test_intent_detection_langchain.sh
Fix intent detection code issue & refine ci test
ci test failed in [reorg pr](https://github.com/opea-project/GenAIComps/pull/625)
Add `uvicorn` in `requirements.txt`
Local tested
> Fix intent detection code issue

- comps/finetuning/handlers.py
- tests/test_finetuning_embedding_hpu.sh
> add resume finetuning checkpoint ut.

- comps/lvms/video-llama/dependency/server.py
- tests/lvms/test_lvms_video-llama.sh
Fix lvms videl-llama code issue.
Modify hard code file path in `dependency/server.py`.
Refine test script.
CI test failed in [reorg pr](https://github.com/opea-project/GenAIComps/pull/625)
None
Local tested.
> Fix lvms videl-llama code issue

- comps/intent_detection/langchain/intent_detection.py
- comps/llms/text-generation/vllm/langchain/dependency/build_docker_vllm.sh
- comps/lvms/tgi-llava/template.py
- tests/embeddings/test_embeddings_tei_langchain.sh
- tests/intent_detection/test_intent_detection_langchain.sh
Fix reorg issues of [PR 625](https://github.com/opea-project/GenAIComps/pull/625)
Issues in https://github.com/opea-project/GenAIComps/pull/625.
None
Local test + CI test
> Fix Reorg Issues

- .github/workflows/scripts/get_test_matrix.sh
> minor fix for CI detect

- comps/agent/langchain/src/strategy/ragagent/planner.py
The "query_time" needs to be initialized with an empty string. Otherwise the agent will error.
na
no
unit test
> fix ragagent text generator bug

- .github/workflows/scripts/get_test_matrix.sh
omit full test due to __init__.py|version.py file change
> optimize ci test scope

- .github/workflows/pr-dockerfile-path-scan.yaml
temp remove dockerfile check
https://github.com/opea-project/GenAIComps/actions/runs/10809577508/job/29984985161?pr=667
> temp remove dockerfile check

- .pre-commit-config.yaml
- tests/cores/mega/ChatQnA_E2E_manifests_base.yaml
> Fixed CI yaml

- comps/retrievers/qdrant/haystack/requirements.txt
- comps/retrievers/qdrant/haystack/retriever_qdrant.py
issue from  https://github.com/opea-project/GenAIComps/pull/426
> Fix security problem

- comps/llms/text-generation/vllm/llama_index/llm.py
fix bug for PR https://github.com/opea-project/GenAIComps/pull/665
> fix vllm llamaindex stream bug

- comps/__init__.py
- comps/cores/mega/constants.py
- comps/cores/mega/gateway.py
- comps/dataprep/multimodal/redis/langchain/README.md
- comps/dataprep/multimodal/redis/langchain/docker-compose-dataprep-redis.yaml
- comps/embeddings/multimodal/README.md
- comps/embeddings/multimodal/bridgetower/docker_compose_bridgetower_embedding_endpoint.yaml
- comps/embeddings/multimodal/multimodal_langchain/docker_compose_multimodal_embedding.yaml
- comps/lvms/llava/README.md
- comps/lvms/llava/lvm.py
- comps/lvms/tgi-llava/lvm_tgi.py
- comps/retrievers/multimodal/redis/langchain/README.md
- comps/retrievers/multimodal/redis/langchain/docker_compose_retriever.yaml
- tests/cores/mega/test_multimodalqna_gateway.py
- tests/dataprep/test_dataprep_multimodal_redis_langchain.sh
- tests/embeddings/test_embeddings_multimodal.sh
- tests/embeddings/test_embeddings_multimodal_on_intel_hpu.sh
- tests/lvms/test_lvms_llava.sh
- tests/retrievers/test_retrievers_multimodal_redis_langchain.sh
Update image names for embedding, dataprep, retriever, lvm microservices.
Update MultimodalQnAGateway
MultimodalRAG for v1.0 release
- [x ] Others (enhancement, documentation, validation, etc.)
N/A
All tests predefined for embedding, dataprep, retriever, lvm microservices for multimodal.
Test for MultimodalQnAGateway
> Update example name into MultimodalQnA and update image names

- tests/embeddings/test_embeddings_tei_langchain.sh
Update embedding svc test port numbert.
`n/a`.
None
Local test
> Update embedding svc test port number

- .github/workflows/_run-docker-compose.yml
> Update manual test.

- comps/dataprep/vdms/README.md
- comps/dataprep/vdms/multimodal_langchain/README.md
* Only one H1 for the title is allowed
* remove uses of please (in files I was fixing the headings)
* Fix indenting under a list
> doc: fix heading levels

- .github/workflows/docker/compose/guardrails-compose-cd.yaml
- .github/workflows/docker/compose/guardrails-compose.yaml
> Adding Bias Detection Container to CI

- README.md
add contributing section to main readme with link to contributing guide
cc: @mkbhanda @chensuyue @kding1
> add contributing section to main readme

- .github/workflows/pr-microservice-test.yml
> update ci action

- comps/llms/text-generation/ollama/langchain/requirements.txt
Fix Ollama langchain upgrade issue
`n/a`
None
Local test
> Fix Ollama langchain upgrade issue

- comps/intent_detection/langchain/requirements.txt
- comps/llms/faq-generation/tgi/langchain/requirements.txt
- comps/llms/requirements.txt
- comps/llms/text-generation/ray_serve/requirements.txt
- comps/llms/text-generation/vllm/ray/requirements.txt
- comps/ragas/tgi/langchain/requirements.txt
Fix all the microservices which affected by langchain version upgrade
`n/a`
None
Local test
> Fix all the microservices which affected by langchain version upgrade

- README.md
Update README.md for broken/missing readme.md file in Comps README table
> Update README.md for broken/missing readme

- comps/llms/text-generation/vllm/ray/README.md
Update README.md for Gaudi & Multiplatforms
> Update README.md for Multiplatforms

- comps/embeddings/predictionguard/README.md
- comps/llms/text-generation/predictionguard/README.md
- comps/lvms/predictionguard/README.md
Only one H1 heading with the title is allowed.  The rest must be H2 and deeper, so adjust them accordingly.
> doc: Fix headings

- README.md
same as #694 but on the main branch
cc: @chensuyue
> same PR as #694 but on main branch

- comps/llms/text-generation/vllm/langchain/dependency/Dockerfile.intel_hpu
update vllm to latest version for hpu
> update vllm to latest version for hpu

- comps/agent/langchain/requirements.txt
- comps/dataprep/multimodal/redis/langchain/requirements.txt
- comps/dataprep/redis/langchain/requirements.txt
- comps/lvms/video-llama/dependency/requirements.txt
- comps/retrievers/neo4j/langchain/requirements.txt
Remove fixed version in requirements.txt
`n/a`
None
Local test
> Remove fixed version in requirements.txt

- comps/chathistory/mongo/requirements.txt
- comps/prompt_registry/mongo/requirements.txt
Fix Examples CD Issue
update dependency version of `motor`
https://github.com/opea-project/GenAIExamples/actions/runs/10945495850/job/30411204954
Update dependency version
local tested
> Fix Examples CD Issue for ProductivitySuite

- comps/llms/summarization/tgi/langchain/README.md
- comps/llms/summarization/tgi/langchain/llm.py
summarization-generation/tgi: Fix summarization generation when set streaming to false.
https://github.com/opea-project/GenAIComps/issues/715
N/A
N/A
> summarization-generation/tgi: Fix summarization generation when set streaming to false

- comps/llms/faq-generation/tgi/langchain/README.md
- comps/llms/faq-generation/tgi/langchain/llm.py
faq-generation/tgi: Fix faq-generation when set streaming to false
https://github.com/opea-project/GenAIComps/issues/668
N/A
N/A
> faq-generation/tgi: Fix faq-generation when set streaming to false

- comps/agent/langchain/README.md
- comps/agent/langchain/agent.py
- comps/agent/langchain/src/utils.py
fix agent comps issue
* fix format bug when LOGFLAG  is on
* fix default strategy from "react" to "react_langchain" and corresponding usage in README
None
Local test
> fix agent comps minor issues

- comps/llms/text-generation/vllm/langchain/llm.py
At present, the implementation of VLLM microservice will greatly affect the performance. Improved this part of the code to enhance performance.
`n/a`.
- [ *] Others (enhancement, documentation, validation, etc.)
> Fix vllm microservice performance issue. 

- comps/embeddings/tei/langchain/embedding_tei.py
- comps/embeddings/tei/langchain/local_embedding.py
- comps/embeddings/tei/langchain/local_embedding_768.py
- comps/embeddings/tei/llama_index/embedding_tei.py
- comps/embeddings/tei/llama_index/local_embedding.py
Support async in embedding micorservice
`n/a`.
None
Local test
> Support async for embedding micorservice

- comps/finetuning/README.md
Replaced Optional with Option in  https://github.com/opea-project/GenAIComps/blob/main/comps/finetuning/README.md.
> Replaced Optional with Option.

- comps/dataprep/milvus/langchain/docker-compose.yml
- comps/dataprep/milvus/langchain/milvus.yaml
- tests/dataprep/test_dataprep_milvus_langchain.sh
Change port for avoid port conflicts.
> Change port for avoid port conflicts.

- comps/reranks/tei/reranking_tei.py
TEI rerank microservice async support 
`n/a`
None
Local test
> TEI rerank microservice async support 

- comps/dataprep/pinecone/langchain/Dockerfile
- comps/lvms/llava/Dockerfile
- comps/lvms/tgi-llava/Dockerfile
- comps/reranks/fastrag/Dockerfile
- comps/retrievers/redis/llama_index/Dockerfile
- comps/retrievers/redis/llama_index/requirements.txt
This PR is primarily to add cpu/gpu option to several Dockerfile's.
None
None
CI tested.
> Misc docker updates

- .github/CODEOWNERS
Update CODEOWNERs.
N/A
N/A
N/A
> CODEOWNER: Update comp CODEOWNER

- .github/workflows/mix-megaservice-test.yml
> Add timeout for ut test

- .github/workflows/_run-docker-compose.yml
> Fix manual test issue

- .github/workflows/pr-dockerfile-path-scan.yaml
Fix the issue of exiting due to inability to find hyperlinks.
> Fix the issue of exiting due to inability to find hyperlinks.

- .pre-commit-config.yaml
Update docformatter in pre-commit
> Update docformatter in pre-commit

- .github/workflows/pr-examples-test.yml
revert test code
pull_request couldn't get GHA secrets
> revert test code

- comps/nginx/nginx.conf.template
Fix nginx streaming without caching the response
`n/a`
None
Local test
> Fix nginx streaming without caching the response

- comps/tts/gpt-sovits/Dockerfile
Add some critical params which can boost 3~4x inference speedup on xeon
na
na
na
> add optimization params to gpt-sovits

- .github/workflows/pr-dockerfile-path-scan.yaml
> Add prompt output.

- comps/feedback_management/mongo/requirements.txt
Remove fixed version for motor packages
n/a
n/a
> feedback_management: Fix mongo dependencies version

- comps/nginx/nginx.conf.template
Update nginx config template
`n/a`
None
Local test
> Update nginx config template

- comps/asr/whisper/dependency/whisper_model.py
fix whisper hpu and long form issue
https://github.com/opea-project/GenAIComps/issues/817
https://github.com/opea-project/GenAIExamples/pull/923
na
local test
> fix whisper hpu and long form issue

- comps/cores/mega/gateway.py
> Set a higher default value(1.2) about repetition_penalty for codegen example to reduce repetition

- comps/cores/mega/gateway.py
Fix docsum crash issue for text summary case
`n/a`
None
Local test
> Fix docsum crash issue for text summary case

- comps/agent/langchain/src/tools.py
change pydantic import in utils.py to fix the tool_renderer error.
`n/a`.
No newly introduced 3rd party dependency.
Unit test
> fix pydantic version in agent component

- comps/llms/text-generation/native/langchain/README.md
- comps/llms/text-generation/native/langchain/docker_compose_llm.yaml
- comps/llms/text-generation/native/langchain/utils.py
Add huggingface token for native llm
> Add huggingface token for native llm

- comps/dataprep/neo4j/llama_index/README.md
fix format issue to break building online doc.
> fix format issue

- .github/workflows/scripts/freeze_images.sh
- comps/animation/wav2lip/dependency/Dockerfile.intel_hpu
- comps/asr/whisper/dependency/Dockerfile.intel_hpu
- comps/embeddings/multimodal/bridgetower/Dockerfile.intel_hpu
- comps/finetuning/Dockerfile.intel_hpu
- comps/image2image/Dockerfile.intel_hpu
- comps/image2video/dependency/Dockerfile.intel_hpu
- comps/llms/text-generation/native/langchain/Dockerfile
- comps/llms/text-generation/native/llama_index/Dockerfile
- comps/llms/text-generation/vllm/langchain/dependency/Dockerfile.intel_hpu
- comps/llms/text-generation/vllm/llama_index/dependency/Dockerfile.intel_hpu
- comps/llms/text-generation/vllm/ray/dependency/Dockerfile
- comps/lvms/llama-vision/Dockerfile
- comps/lvms/llama-vision/Dockerfile_guard
- comps/lvms/llama-vision/Dockerfile_tp
- comps/lvms/llava/dependency/Dockerfile.intel_hpu
- comps/text2image/Dockerfile.intel_hpu
- comps/tts/speecht5/dependency/Dockerfile.intel_hpu
- tests/llms/test_llms_text-generation_vllm_ray_on_intel_hpu.sh
Upgrade habana docker version to 1.18.0
`n/a`
None
Local test
> Upgrade habana docker version to 1.18.0

- comps/cores/mega/gateway.py
support faqgen upload file in UI
> support faqgen upload file in UI

- comps/llms/text-generation/vllm/langchain/README.md
> fix doc format issue

- comps/embeddings/mosec/langchain/embedding_mosec.py
> Fixed the issue of asynchronous call failure for MosecEmbeddings

- comps/llms/summarization/tgi/langchain/README.md
- comps/llms/text-generation/README.md
- comps/llms/text-generation/tgi/README.md
- comps/llms/text-generation/vllm/langchain/README.md
- comps/llms/text-generation/vllm/llama_index/README.md
Update llm endpoint validation commands.
Unify curl command to `/v1/chat/completions` for both `TGI` and `vLLM` endpoints.
n/a
None
Local tested
> Update LLM Endpoint Validation Commands

- tests/llms/test_llms_text-generation_vllm_langchain_openvino_on_intel_arc.sh
Enable Intel ARC gpu test for vllm openvino.
n/a.
> Add Intel ARC GPU test for vllm openvino.

- comps/cores/mega/gateway.py
Added langchain vLLM support for  Code Generation. 
Since model is mandatory parameter for vLLM updated the CodeGenGateway to include the new parameter called "model" in Mega service gateway.py file
N/A
N/A
> vLLM support for Codegen

- .github/workflows/pr-dockerfile-path-scan.yaml
Block links that require real person verification.
> Block links that require real person verification

- comps/cores/mega/gateway.py
Fix for docsum gateway 
Docsum Gateway Fix
N/A
CI test
> Docsum Gateway Fix

- comps/tts/gpt-sovits/README.md
Add some instructions to use the zero-shot voice cloning feature. Provide switch to a default male voice.
na
na
na
> add zero-shot voice cloning readme

- comps/cores/mega/gateway.py
- comps/cores/proto/api_protocol.py
Pass down model id for ChatQnA
`n/a`
None
CI test
> Add env for pass down model id in ChatQnA gateway

- .github/workflows/_run-docker-compose.yml
Fix hardware label retrieval issue
> Fix hardware label retrieval issue

- .github/workflows/_comps-workflow.yml
- .github/workflows/docker/compose/llms-compose.yaml
- .github/workflows/docker/compose/lvms-compose.yaml
- comps/agent/langchain/README.md
- comps/llms/faq-generation/vllm/langchain/README.md
- comps/llms/faq-generation/vllm/langchain/docker_compose_llm.yaml
- comps/llms/summarization/vllm/langchain/README.md
- comps/llms/summarization/vllm/langchain/docker_compose_llm.yaml
- comps/llms/text-generation/vllm/langchain/dependency/build_docker_vllm.sh
- comps/llms/text-generation/vllm/langchain/dependency/launch_vllm_service.sh
- comps/llms/text-generation/vllm/langchain/docker_compose_llm.yaml
- comps/llms/text-generation/vllm/llama_index/dependency/build_docker_vllm.sh
- comps/llms/text-generation/vllm/llama_index/dependency/launch_vllm_service.sh
- comps/llms/text-generation/vllm/llama_index/docker_compose_llm.yaml
- tests/agent/test_agent_langchain_on_intel_hpu.sh
- tests/llms/test_llms_text-generation_vllm_langchain_on_intel_hpu.sh
- tests/llms/test_llms_text-generation_vllm_llamaindex_on_intel_hpu.sh
Rename image names XXX-hpu to XXX-gaudi
> Rename image names XXX-hpu to XXX-gaudi

- .github/workflows/_run-docker-compose.yml
- .github/workflows/pr-dockerfile-path-scan.yaml
> Fix CD issues

- .github/workflows/docker/compose/texttosql-compose.yaml
> fix the image name

- comps/version.py
bump release version into v1.1
> bump release version into v1.1

- tests/retrievers/test_retrievers_pathway_langchain.sh
Fix opea/retriever-pathway:comps build issue
> Fix opea/retriever-pathway:comps build issue

- .github/workflows/docker/compose/intent_detection-compose.yaml
- .github/workflows/pr-check-duplicated-image.yml
- .github/workflows/scripts/check_duplicated_image.py
- comps/intent_detection/langchain/README.md
- comps/intent_detection/langchain/docker_compose_intent.yaml
- tests/intent_detection/test_intent_detection_langchain.sh
- Add check for conflict image build definition which generate the same image name with conflict content
- Use unified image name intent-detection-tgi for intent detection
`n/a`.
- [c] Others (enhancement, documentation, validation, etc.)
n/a.
> CI: Add check for conflict image build definition

- comps/tts/speecht5/requirements.txt
> Add dependence for speech5

- tests/asr/test_asr_whisper_on_intel_hpu.sh
- tests/tts/test_gpt_sovits.sh
- tests/tts/test_tts_speecht5.sh
- tests/tts/test_tts_speecht5_on_intel_hpu.sh
Enhance asr/tts tests. All missing tests are added.
[948](https://github.com/opea-project/GenAIComps/issues/948)
NA
Add three tests. Already validated locally.
> Enhance asr/tts tests

- .github/ISSUE_TEMPLATE/1_bug_template.yml
- .github/ISSUE_TEMPLATE/2_feature_template.yml
> add label automatically when create issue

- comps/llms/text-generation/native/langchain/README.md
- comps/llms/text-generation/native/langchain/llm.py
Modify the parameters of llm/native to support falcon3-7b/falcon3-10b models.
n/a
None
Local tested for falcon3-7b/falcon3-10b/qwen-2 models.
> [LLM] Modify Params to Support Falcon3 Model

- comps/llms/text-generation/tgi/README.md
- comps/llms/text-generation/tgi/launch_tgi_service.sh
- comps/llms/text-generation/tgi/requirements.txt
- tests/llms/test_llms_text-generation_tgi.sh
refine tgi doc with default openai input/output format.
> refine tgi doc.

- comps/retrievers/redis/langchain/retriever_redis.py
Fix MultimodalQnA Issue
https://github.com/opea-project/GenAIExamples/pull/1252
None
Local tested
> Fix MultimodalQnA Issue

- .github/workflows/pr-examples-test.yml
- .github/workflows/pr-microservice-test.yml
- .github/workflows/scripts/get_test_matrix.sh
Update CI test adapt the new code org.
> Refactor comps ci

- comps/retrievers/pinecone/langchain/Dockerfile
> fix retrievers pinecone

- comps/dataprep/redis/llama_index/prepare_doc_redis.py
- comps/dataprep/redis/llama_index/redis_llama_index.yaml
- tests/dataprep/test_dataprep_redis_llama_index.sh
> Fix dataprep redis llama_index

- comps/dataprep/redis/langchain_ray/prepare_doc_redis_on_ray.py
- tests/dataprep/test_dataprep_redis_langchain_ray.sh
> Fix redis langchain ray ci issue

- comps/retrievers/src/integrations/config.py
- comps/retrievers/src/integrations/redis.py
- comps/retrievers/src/opea_retrievers_microservice.py
Merge multimodal retrievers
for DocIndexRetriever example ci
None
Local tested
> Add multimodal retrievers

- .github/workflows/docker/compose/nginx-compose.yaml
- tests/3rd_parties/test_3rd_parties_nginx.sh
> fix nginx test path

- .github/workflows/push-image-build.yml
- .github/workflows/scripts/get_test_matrix.sh
Fix changed file detect issue while generate test matrix.
> Fix changed file detect issue

- .github/CODEOWNERS
In .github/CODEOWNERS the last pattern go first, so need to adjust the list.
> Fix code owner list

- .github/license_template.txt
Change license template 2024 to 2025
> Change license template from 2024 to 2025

- comps/agent/src/README.md
- comps/agent/src/integrations/utils.py
Although openai chat completion request use `stream` as input, we need pass `streaming` field when we use `from langchain_openai import ChatOpenAI` or `rom langchain_huggingface import HuggingFaceEndpoint`
fix the issue caused by this https://github.com/opea-project/GenAIComps/pull/1098
> fix stream issue.

- .github/workflows/push-infra-issue-creation.yml
Automatically create issue in CIInfra to track the changes of docker compose files for correspdonding helm charts.
`n/a`.
> CI: Automatically create issue in CIInfra

- .github/workflows/manual-freeze-images.yml
- .github/workflows/manual-freeze-requirements.yml
- .github/workflows/push-infra-issue-creation.yml
> Update action token for CI

- .github/workflows/_comps-workflow.yml
- comps/third_parties/vllm/src/build_docker_vllm.sh
- tests/llms/test_llms_doc-summarization_langchain_vllm_on_intel_hpu.sh
- tests/llms/test_llms_faq-generation_langchain_vllm_on_intel_hpu.sh
- tests/llms/test_llms_text-generation_opea_vllm_on_intel_hpu.sh
Before add this version limit to avoid main branch bug, now remove it.
> Remove vllm hpu commit id limit

- comps/animation/src/requirements.txt
In animation/wav2lip component on Gaudi, a module that was compiled using NumPy 1.x cannot be run in NumPy 2.0.2 as it may crash. So we set numpy's version to 1.23.5.
```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.
(Triggered internally at /npu-stack/pytorch-fork/torch/csrc/utils/tensor_numpy.cpp:84.)
cpu = _conversion_method_template(device=torch.device("cpu"))
Calling add_step_closure function does not …
```
> Set the wav2lip's numpy version to 1.23.5 to ensure that there are no version mismatch errors in the Gaudi image

- comps/asr/src/README.md
Fix wrong link in asr doc
na
na
na
> Fix wrong link in asr doc

- .github/workflows/pr-microservice-test.yml
Enhance docker container clean up in CI
> Enhance docker container clean up in CI

- comps/agent/deployment/kubernetes/gaudi-values.yaml
- comps/dataprep/deployment/kubernetes/milvus-values.yaml
- comps/retrievers/deployment/kubernetes/milvus-values.yaml
- comps/text2image/deployment/kubernetes/README.md
- comps/text2image/deployment/kubernetes/cpu-values.yaml
- comps/text2image/deployment/kubernetes/gaudi-values.yaml
- comps/third_parties/bridgetower/deployment/kubernetes/README.md
- comps/third_parties/bridgetower/deployment/kubernetes/cpu-values.yaml
- comps/third_parties/bridgetower/deployment/kubernetes/gaudi-values.yaml
- comps/third_parties/tgi/deployment/kubernetes/gaudi-values.yaml
milvus-values, llm/cpu-values changed.
text2image values new added.
Sync values from GenAIInfra helm chart changes.
> Sync values from GenAIInfra

- comps/finetuning/deployment/docker_compose/compose.yaml
- comps/image2video/deployment/docker_compose/compose.yaml
- comps/text2image/deployment/docker_compose/compose.yaml
- tests/finetuning/test_finetuning_native.sh
- tests/finetuning/test_finetuning_native_on_intel_hpu.sh
- tests/image2video/test_image2video_native.sh
- tests/image2video/test_image2video_native_on_intel_hpu.sh
- tests/text2image/test_text2image_native.sh
- tests/text2image/test_text2image_native_on_intel_hpu.sh
Added compose yaml for text2image, image2video and finetuning, also adjusted corresponding UT.
`n/a`.
no.
UT itself.
> Add compose yaml for text2image, image2video and finetuning

- comps/version.py
bump release version into v1.2
> bump release version into v1.2

- .github/workflows/pr-microservice-test.yml
Add permissions for Bedrock CI
> Add permissions for Bedrock CI

- comps/third_parties/vllm/deployment/docker_compose/compose.yaml
- tests/third_parties/test_third_parties_vllm_openvino.sh
- tests/third_parties/test_third_parties_vllm_openvino_on_intel_arc.sh
support docker compose  and ut for  third-party vllm-openvino
`n/a`.
no
tests/third_parties/test_third_parties_vllm_openvino.sh
tests/third_parties/test_third_parties_vllm_openvino_on_intel_arc.sh
> Refactor docker compose for vllm-openvino

- comps/asr/src/README.md
- comps/lvms/src/README.md
- comps/tts/src/README.md
- comps/web_retrievers/src/README.md
add asr/tts/web_retrievers/lvms docker compose readme
na
na
na
> add asr/tts/web_retrievers/lvms docker compose readme

- comps/animation/src/README.md
- comps/image2image/src/README.md
- comps/text2sql/src/README.md
Refine Readme in animation/image2image/text2sql about start service via docker compose
`n/a`.
None
None
> Refine Readme in animation/image2image/text2sql about start service via docker compose

- comps/embeddings/src/README.md
- comps/embeddings/src/README_bridgetower.md
- comps/embeddings/src/README_predictionguard.md
- comps/embeddings/src/README_tei.md
Refine embedding microservice document
`n/a`
None
Just documents refine
> Refine embedding microservice document

- comps/finetuning/src/README.md
- comps/image2video/src/README.md
- comps/text2image/src/README.md
Updated readme of text2image,image2video and finetuning for docker compose.
`n/a`.
> Updated readme of text2image,image2video and finetuning for docker compose

- comps/third_parties/vllm/README.md
Fix minor doc issue in vllm component
`n/a`.
`n/a`.
`n/a`.
> doc: fix minor issue in vllm doc

- comps/llms/src/doc-summarization/integrations/tgi.py
Error when using Docsum with TGI
>  File "/home/user/comps/llms/src/doc-summarization/integrations/tgi.py", line 75, in invoke                                                                                                     
>     result = await self.generate(input, self.client)                                                                                                                                             
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                             
>   File "/home/user/comps/llms/src/doc-summarization/integrations/common.py", line 206, in generate …
> [bugfix] docsum error by HuggingFaceEndpoint 

- comps/embeddings/src/integrations/tei.py
- comps/rerankings/src/integrations/tei.py
TEI embedding and reranking microservices throw error: [   ERROR] - opea_embedding_microservice - Error during embedding invocation: Task text-embedding has no recommended model. Please specify a model explicitly. This is due to model (ie endpoint url) was not passed in the post method.
https://github.com/opea-project/GenAIComps/issues/1255
No new dependencies
UTs
> fix tei embedding and tei reranking bug

- .github/workflows/manual-comps-test.yml
- .github/workflows/manual-docker-publish.yml
Update default service list for GHA jobs. 
> update default service list

- .github/workflows/docker/compose/chathistory-compose.yaml
- comps/chathistory/deployment/docker_compose/compose.yaml
- comps/chathistory/src/README.md
- tests/chathistory/test_chathistory_mongo.sh
- chathistory-mongo-server -> chathistory-mongo (except container names)
- feedbackmanagement -> feedbackmanagement-mongo
- promptregistry-server/promptregistry-mongo-server -> promptregistry-mongo (except container names)
https://github.com/opea-project/GenAIExamples/pull/1543
na
na
> Align chathistory/feedbackmanagement/promptregistry image names

- comps/retrievers/deployment/docker_compose/compose.yaml
- comps/retrievers/src/integrations/qdrant.py
- comps/retrievers/src/opea_retrievers_microservice.py
Fix Qdrant retriever no retrieved result issue.
Unify the index name for Qdrant, and update the logic in qdrant.py
https://github.com/opea-project/GenAIExamples/issues/1473
None
Local tested
> Fix Qdrant retriever RAG issue.

- comps/embeddings/deployment/docker_compose/compose.yaml
- comps/embeddings/src/integrations/clip.py
- comps/embeddings/src/requirements.txt
- comps/third_parties/clip/deployment/docker_compose/compose_intel_cpu.yaml
- tests/embeddings/test_embeddings_clip.sh
Refine CLIP embedding microservice by leveraging the third-party CLIP
Fixes #1295
None
Local test and CI test.
> Refine CLIP embedding microservice by leveraging the third-party CLIP

- comps/agent/src/README.md
- comps/agent/src/integrations/strategy/react/planner.py
1. set default `session_id` for `react_langchain` strategy, because the langchain version upgrade.
2. fix request message format
> fix agent message format.

- comps/dataprep/deployment/docker_compose/compose.yaml
- tests/dataprep/test_dataprep_elasticsearch.sh
- tests/dataprep/test_dataprep_milvus.sh
- tests/dataprep/test_dataprep_neo4j_on_intel_hpu.sh
- tests/dataprep/test_dataprep_opensearch.sh
- tests/dataprep/test_dataprep_pgvector.sh
- tests/dataprep/test_dataprep_pinecone.sh
- tests/dataprep/test_dataprep_qdrant.sh
- tests/dataprep/test_dataprep_redis.sh
- tests/dataprep/test_dataprep_vdms.sh
Integrate milvus docker compose yaml in dataprep.
Start related services with single command in CI test script.
Refine dataprep test scripts of docker image TAG.
n/a
None
Local tested
> Refine dataprep test scripts

- comps/asr/src/integrations/dependency/whisper/Dockerfile.intel_hpu
https://github.com/opea-project/GenAIComps/issues/1309
> Fix docker image security issues

- comps/dataprep/src/requirements.txt
- comps/retrievers/src/Dockerfile
- comps/retrievers/src/requirements.txt
Fix NLTK_DATA path issue due to llama_index version upgrade
Fix the same issue for retrievers, https://github.com/opea-project/GenAIComps/issues/1332. 
> fix NLTK_DATA path issue due to llama_index version update

- comps/prompt_registry/README.md
> doc: spell check update

- .github/workflows/push-base-image-upstream.yml
update image upstream machine, add more machines for image upstream. 
> update image upstream machine

- .github/workflows/daily_check_issue_and_pr.yml
Add GitHub Action to check and close stale issues and PRs
`n/a`
> Add GitHub Action to check and close stale issues and PRs

- comps/dataprep/deployment/docker_compose/compose.yaml
- comps/dataprep/src/integrations/milvus_multimodal.py
- comps/dataprep/src/opea_dataprep_multimodal_microservice.py
- tests/dataprep/test_dataprep_milvus_multimodal.sh
[Bug: 1378] Added Multimodal support for Milvus for dataprep component
Fixes #1378
Co-authored-by: Jaini, Pallavi <pallavi.jaini@intel.com>
Signed-off-by:  Ghosh, Soumyadip <soumyadip.ghosh@intel.com>
Signed-off-by:  Piroozan, Nariman <nariman.piroozan@intel.com>
Signed-off-by: Kavulya, Soila <soila.kavulya@intel.com>
Signed-off-by: Rajabose, Shifani <shifani.rajabose@intel.com>
Added Multimodal support for Milvus for dataprep component
https://github.com/opea-project/GenAIComps/issues/1378
- [* ] New feature (non-breaking change which adds new functionality)
- [ *] Others (enhancement, documentation, validation, etc.)
n/a
Ingestion of  audio, video, pdf and image are tested
> [Bug: 1378] Added Multimodal support for Milvus for dataprep component

- comps/third_parties/vllm/src/Dockerfile.intel_gpu
- tests/third_parties/test_third_parties_vllm_openvino_on_intel_arc.sh
Build Dockerfile.intel_gpu will fail because low pip version, upgrade pip could solve the issue
Fix Dockerfile.intel_gpu build issue
Build Dockerfile.intel_gpu will fail because low pip version, upgrade pip could solve the issue
n/a
- [ √] Bug fix (non-breaking change which fixes an issue)
> Fix Dockerfile.intel_gpu build issue

- comps/llms/src/doc-summarization/README.md
> Refine the README for llms/doc-summarization

- .github/workflows/pr-examples-test.yml
- .github/workflows/pr-microservice-test.yml
1. Enhance docker clean up in CI
2. Remove invalid label after cluster migrate
> Enhance docker clean up in CI

- .github/workflows/pr-microservice-test.yml
- tests/agent/test_agent_langchain_on_intel_hpu.sh
- tests/dataprep/test_dataprep_redis_finance_on_intel_hpu.sh
1. Fix default model cache adapt to the new test cluster
2. Skip docker build container clean up for microservice test
https://github.com/opea-project/GenAIComps/actions/runs/14028271842/job/39270707359?pr=1317#step:5:8155
> Fix default model cache adapt to the new test cluster

- tests/llms/test_llms_doc-summarization_tgi_on_intel_hpu.sh
- tests/llms/test_llms_doc-summarization_vllm_on_intel_hpu.sh
- tests/llms/test_llms_faq-generation_tgi_on_intel_hpu.sh
- tests/llms/test_llms_faq-generation_vllm_on_intel_hpu.sh
- tests/llms/test_llms_text-generation_native_on_intel_hpu.sh
- tests/llms/test_llms_text-generation_service_tgi_on_intel_hpu.sh
- tests/llms/test_llms_text-generation_service_vllm_on_intel_hpu.sh
- tests/retrievers/test_retrievers_neo4j_on_intel_hpu.sh
Update default model cache for new CI cluster. 
https://github.com/opea-project/GenAIComps/actions/runs/14031733483/job/39280713958?pr=1317#step:5:6214 
> Update default model cache for new CI cluster

- comps/retrievers/src/opea_retrievers_microservice.py
Refactor the function name of retriever microservice
n/a
None
> Fix Retriever Function Name Issue

- comps/third_parties/tei/deployment/docker_compose/compose.yaml
- tests/embeddings/test_embeddings_tei.sh
Use model cache for embeddings docker compose test.
> Use model cache for embeddings docker compose test.

- comps/web_retrievers/deployment/docker_compose/compose.yaml
- tests/web_retrievers/test_web_retrievers_google_search.sh
Use model cache for web_retriever docker compose test.
> Use model cache for web_retriever docker compose test.

- tests/rerankings/test_rerankings_tei.sh
- tests/rerankings/test_rerankings_tei_on_intel_hpu.sh
Use model cache for rerankings docker compose test.
> Use model cache for rerankings docker compose test.

- tests/retrievers/test_retrievers_milvus.sh
- tests/retrievers/test_retrievers_neo4j_on_intel_hpu.sh
- tests/retrievers/test_retrievers_opensearch.sh
- tests/retrievers/test_retrievers_pathway.sh
- tests/retrievers/test_retrievers_vdms.sh
Use model cache for retrievers docker compose test.
> Use model cache for retrievers docker compose test.

- tests/llms/test_llms_doc-summarization_tgi.sh
- tests/llms/test_llms_doc-summarization_tgi_on_intel_hpu.sh
- tests/llms/test_llms_doc-summarization_vllm.sh
- tests/llms/test_llms_doc-summarization_vllm_on_intel_hpu.sh
- tests/llms/test_llms_faq-generation_tgi.sh
- tests/llms/test_llms_faq-generation_tgi_on_intel_hpu.sh
- tests/llms/test_llms_faq-generation_vllm.sh
- tests/llms/test_llms_faq-generation_vllm_on_intel_hpu.sh
- tests/llms/test_llms_text-generation_native_on_intel_hpu.sh
- tests/llms/test_llms_text-generation_service_tgi.sh
- tests/llms/test_llms_text-generation_service_tgi_on_intel_hpu.sh
- tests/llms/test_llms_text-generation_service_vllm_on_intel_hpu.sh
Use model cache for llms docker compose test.
> Use model cache for llms docker compose test.

- comps/dataprep/src/README_finance.md
- comps/dataprep/src/README_milvus.md
- comps/dataprep/src/README_opensearch.md
- comps/dataprep/src/README_redis.md
- comps/embeddings/src/README_tei.md
- comps/rerankings/src/README_tei.md
- comps/retrievers/src/README_elasticsearch.md
- comps/retrievers/src/README_opensearch.md
- comps/retrievers/src/README_pathway.md
- comps/retrievers/src/README_pgvector.md
- comps/retrievers/src/README_redis.md
- comps/retrievers/src/README_vdms.md
- comps/third_parties/tei/deployment/docker_compose/compose.yaml
- comps/web_retrievers/deployment/docker_compose/compose.yaml
- comps/web_retrievers/src/README.md
- tests/cores/mega/ChatQnA_E2E_manifests_base.yaml
- tests/cores/mega/mega.yaml
- tests/dataprep/test_dataprep_neo4j_on_intel_hpu.sh
- tests/retrievers/test_retrievers_neo4j_on_intel_hpu.sh
- tests/third_parties/test_third_parties_pathway.sh
update TEI docker image to ghcr.io/huggingface/text-embeddings-inference:cpu-1.6
Fix https://github.com/opea-project/GenAIExamples/issues/1640
No
> Update TEI docker image to 1.6

- .github/workflows/_run-docker-compose.yml
- .github/workflows/pr-examples-test.yml
Enhance test env clean up for docker and port. 
> Enhance test env clean up

- comps/third_parties/nginx/deployment/docker_compose/start-nginx.sh
- comps/third_parties/nginx/src/Dockerfile
- comps/third_parties/nginx/src/nginx.conf.template
- tests/third_parties/test_third_parties_nginx.sh
This reverts commit d58d320f82d556ff93b412a2522879181d5130ed.
This fix will affect the examples test, so revert first, and @xiguiw will fix with another PR.
> Revert "Support parametrization of nginx port (#1456)"

- .github/workflows/pr-examples-test.yml
Add nginx src into example test trigger path, so CI will trigger chatqna test on gaudi when the src code updated. 
> Add nginx src into example test trigger path

- tests/embeddings/test_embeddings_ovms.sh
- tests/llms/test_llms_text-generation_service_ovms.sh
- tests/rerankings/test_reranking_ovms.sh
Resolve false positive errors in CI while resetting permissions in HF cache files
https://github.com/opea-project/GenAIComps/issues/1481
n/a
CI tests execution
> ignore false positive errors in reseting cache permissions

- requirements.txt
Remove langchain-huggingface from requirement.
> Remove langchain-huggingface from requirement.

- .github/workflows/pr-examples-test.yml
add model cache for example test
> add model cache for example test

- .github/workflows/_run-helm-chart.yml
> Fix model cache path and use Random to avoid ns conflict

- .github/workflows/pr-microservice-test.yml
Fix CI workflow, remove invalid pattern. 
> Fix CI workflow

- comps/agent/deployment/kubernetes/gaudi-values.yaml
- comps/dataprep/deployment/kubernetes/qdrant-values.yaml
- comps/llms/deployment/kubernetes/docsum-values.yaml
- comps/llms/deployment/kubernetes/faqgen-values.yaml
- comps/lvms/deployment/kubernetes/cpu-values.yaml
- comps/retrievers/deployment/kubernetes/qdrant-values.yaml
- comps/third_parties/tei/deployment/kubernetes/gaudi-values.yaml
- comps/third_parties/teirerank/deployment/kubernetes/gaudi-values.yaml
- comps/third_parties/tgi/deployment/kubernetes/cpu-values.yaml
- comps/third_parties/tgi/deployment/kubernetes/gaudi-values.yaml
- comps/third_parties/vllm/deployment/kubernetes/gaudi-values.yaml
Sync the values file for kubernetes deployment
> Sync values yaml file for 1.3 release

- comps/guardrails/src/bias_detection/Dockerfile
- comps/guardrails/src/hallucination_detection/Dockerfile
- comps/image2image/src/Dockerfile
- comps/image2image/src/Dockerfile.intel_hpu
- comps/image2video/src/Dockerfile.intel_hpu
- comps/llms/utils/lm-eval/Dockerfile
- comps/rerankings/src/Dockerfile
- comps/text2image/src/Dockerfile.intel_hpu
- comps/third_parties/bridgetower/src/Dockerfile.intel_hpu
- comps/third_parties/llama-vision/src/Dockerfile
- comps/third_parties/llama-vision/src/Dockerfile.guard
- comps/third_parties/llama-vision/src/Dockerfile.tp
- comps/third_parties/llava/src/Dockerfile.intel_hpu
- comps/third_parties/speecht5/src/Dockerfile.intel_hpu
- comps/third_parties/whisper/src/Dockerfile.intel_hpu
always upgrade setuptools version before deps installation
> always upgrade setuptools version before deps installation

- comps/third_parties/video-llama/src/Dockerfile
- comps/third_parties/video-llama/src/README.md
- comps/third_parties/video-llama/src/docker_compose_vllama.yaml
- comps/third_parties/video-llama/src/requirements.txt
- tests/lvms/test_lvms_video_llama.sh
This PR attempts to upgrade Torch to at leave v2.5.x and audio and vision ecosystem components.
#1306 
None
So far I've tested that the containers at least build fine but more is being conducted.
> Upgrade Torch and it's dependencies to v2.5.x for video-llama

- comps/text2graph/deployment/docker_compose/compose.yaml
- comps/text2sql/deployment/docker_compose/compose.yaml
Unified default port number for the same service in text2graph and text2sql
`n/a`.
None
None
> Unified default port number for the same service in text2graph and text2sql

- comps/llms/src/doc-summarization/integrations/common.py
Follow PR https://github.com/opea-project/GenAIComps/pull/1471
https://github.com/opea-project/GenAIExamples/issues/1810
> Enlarge DocSum prompt buffer

- comps/llms/src/text-generation/Dockerfile.intel_hpu
- comps/llms/src/text-generation/Dockerfile.intel_hpu_phi4
- comps/text2cypher/src/Dockerfile.intel_hpu
- comps/text2image/src/Dockerfile.intel_hpu
- comps/third_parties/bridgetower/src/Dockerfile.intel_hpu
- comps/third_parties/llama-vision/src/Dockerfile
- comps/third_parties/llama-vision/src/Dockerfile.guard
- comps/third_parties/llama-vision/src/Dockerfile.tp
Upgrade Optimum Habana version to fix security check issue
https://github.com/opea-project/GenAIComps/issues/1310 and others.
None
CI test
> Upgrade Optimum Habana version to fix security check issue

- comps/guardrails/src/guardrails/integrations/llamaguard.py
- comps/guardrails/src/guardrails/requirements.txt
- tests/guardrails/test_guardrails_guardrails_llamaguard_on_intel_hpu.sh
Make llamaguard compatible with both TGI and vLLM
`n/a`
None
Local test and CI test
export GUARDRAIL_PORT=9090
curl http://localhost:${GUARDRAIL_PORT}/v1/guardrails  -X POST   -d '{"text":"How do you buy a tiger in the US?","parameters":{"max_new_tokens":32}}'   -H 'Content-Type: application/json'
{"downstream_black_list":[".*"],"id":"7d7b70b47209340d6ab1ead23a3d3e32","text":"Violated policies: Violent Crimes, please check your input."}
> Make llamaguard compatible with both TGI and vLLM

- comps/cores/proto/api_protocol.py
- comps/dataprep/src/integrations/elasticsearch.py
- comps/dataprep/src/integrations/milvus.py
- comps/dataprep/src/integrations/neo4j_langchain.py
- comps/dataprep/src/integrations/neo4j_llamaindex.py
- comps/dataprep/src/integrations/opensearch.py
- comps/dataprep/src/integrations/pgvect.py
- comps/dataprep/src/integrations/pipecone.py
- comps/dataprep/src/integrations/qdrant.py
- comps/dataprep/src/integrations/redis.py
- comps/dataprep/src/integrations/redis_finance.py
- comps/dataprep/src/integrations/vdms.py
- comps/dataprep/src/opea_dataprep_microservice.py
- tests/dataprep/dataprep_utils.sh
- tests/dataprep/test_dataprep_milvus.sh
- tests/dataprep/test_dataprep_redis.sh
This reverts commit 88947ab980c9cdcd5dd4ded1e7a958498438a1d5.
> Revert "new: `DataprepRequest` model (#1525)"

- .github/workflows/_run-helm-chart.yml
Link: https://github.com/opea-project/GenAIComps/actions/runs/14529676939/job/40767284148
> Fix the issue of reporting errors when there are no values files

- comps/guardrails/src/bias_detection/requirements.txt
> Fix guardrails-bias-detection security issue

- comps/dataprep/src/integrations/milvus_multimodal.py
- comps/dataprep/src/integrations/utils/multimodal.py
Fixed the metadata issue with milvus related to b64_img_str
n/a
Bug fix 
> Fixed the metadata issue with milvus related to b64_img_str

- comps/text2graph/src/README.md
- comps/text2sql/src/README.md
- comps/third_parties/tgi/deployment/docker_compose/compose.yaml
Update TGI docker image to 2.4.1
N/A
No
No
> Update TGI docker image to 2.4.1

- comps/third_parties/whisper/src/Dockerfile.intel_hpu
- tests/asr/test_asr_whisper_on_intel_hpu.sh
Fix OH version for Whisper on HPU
https://github.com/opea-project/GenAIComps/issues/1608
Use latest stable OH
UT
> Fix OH version for Whisper on HPU

- comps/cores/mega/micro_service.py
- comps/cores/mega/orchestrator.py
- tests/cores/mega/test_hybrid_service_orchestrator.py
Dynamic remote endpoint switching
NA
NA
> dynamic model switching

- comps/version.py
> Bump version into v1.3

- .github/workflows/push-base-image-upstream.yml
Update base image build workflow
> Update base image build workflow

- tests/cores/mega/test_microservice.py
Fix UT issue caused by bump version
[2025-04-21 15:17:30,653] [    INFO] - Base service - Server termination completed
FAILED
=================================== FAILURES ===================================
_______________________ TestMicroService.test_add_route ________________________
self = <test_microservice.TestMicroService testMethod=test_add_route>
def test_add_route(self):
response = self.client.post("/v1/add", json={"text": "Hello, "})
self.assertEqual(response.status_code, 200)
self.assertEqual(response.json()["text"], "Hello, OPEA Project!")
response = self.client.get("/metrics")
self.assertEqual(response.status_code, 200)
response = self.client.get("/v1/health_check")
>       self.assertEqual(
response.json(),
{"Service Title": "s1", "Version": "1.2", "Service Description": …
> Fix UT issue caused by bump version

- comps/guardrails/README.md
Update the Guardrails main README table to have latest guardrails and added column of contributors
n/a
n/a
n/a
> Update guardrails table

- comps/third_parties/speecht5/src/speecht5_model.py
- comps/tts/src/integrations/speecht5.py
Fix unsafe deserialization security issue
https://github.com/opea-project/GenAIComps/issues/1632
na
ut
code scan
> Fix unsafe deserialization security issue

- comps/third_parties/whisper/src/Dockerfile
Remove NV related package for whisper
https://github.com/opea-project/GenAIComps/actions/runs/14722647384/job/41319183555 test passed
> Remove NV related package

- .github/CODEOWNERS
> Remove invalid codeowner.

- comps/dataprep/src/utils.py
- tests/dataprep/dataprep_utils.sh
- tests/dataprep/test_dataprep_redis.sh
chunk_size and overlap cause type mismatch error in dataprep ingestion service, 
[#1641](https://github.com/opea-project/GenAIComps/issues/1641)
N/A
tests/dataprep/test_dataprep_redis.sh
> bug fix for chunk_size and overlap cause error in dataprep ingestion

- .github/CODEOWNERS
> update PR reviewers

- comps/dataprep/src/integrations/opensearch.py
Fix dataprep opensearch ingest issue.
Default engine for OpenSearch is "nmslib",  but "nmslib" engine is deprecated in OpenSearch and cannot be used for new index creation in OpenSearch from 3.0.0.
File "/usr/local/lib/python3.11/site-packages/langchain_community/vectorstores/opensearch_vector_search.py", line 501, in __add
return _bulk_ingest_embeddings(
^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/langchain_community/vectorstores/opensearch_vector_search.py", line 123, in _bulk_ingest_embeddings
client.indices.create(index=index_name, body=mapping)
File "/usr/local/lib/python3.11/site-packages/opensearchpy/client/utils.py", line 176, in _wrapped
return func(*args, params=params, headers=headers, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
> Fix dataprep opensearch ingest issue

- comps/web_retrievers/deployment/docker_compose/compose.yaml
- comps/web_retrievers/src/opea_web_retrievers_microservice.py
- comps/web_retrievers/src/requirements.txt
- tests/utils/validate_svc_with_mcp.py
- tests/web_retrievers/test_web_retrievers_mcp.sh
add Web Retriever MCP Support
na
mcp
ut
> FEAT(mcp): add Web Retriever MCP Support

- comps/lvms/deployment/docker_compose/compose.yaml
- comps/lvms/src/opea_lvm_microservice.py
- comps/lvms/src/requirements.txt
- tests/lvms/test_lvms_llava_mcp.sh
- tests/utils/validate_svc_with_mcp.py
> FEAT(mcp): add LVM MCP Support

- .github/workflows/pr-examples-test.yml
update secrets token name, `HUGGINGFACEHUB_API_TOKEN` -> `HF_TOKEN`
https://github.com/opea-project/GenAIComps/actions/runs/15151792824/job/42600174017?pr=1718
> update secrets token name

- tests/dataprep/test_dataprep_arango.sh
Update llm model for dataprep_arango test. 
https://github.com/opea-project/GenAIComps/pull/1752, https://github.com/opea-project/GenAIComps/issues/1719
> update llm model for dataprep_arango test

- comps/third_parties/vllm/README.md
Fix invliad link in the document
CI failure
Valid the link
> Fix borken document link

- .github/workflows/mix-megaservice-test.yml
Remove pytest cache while test cancelled. 
https://github.com/opea-project/GenAIComps/actions/runs/15180873434/job/42689835388?pr=1678
> Remove pytest cache while test cancelled

- comps/llms/src/faq-generation/Dockerfile
- comps/llms/src/faq-generation/entrypoint.sh
- comps/llms/src/faq-generation/integrations/common.py
- comps/llms/src/faq-generation/requirements-runtime.txt
Replace langserve.serialization with langchain's own serialization functions.
Partial resolution to issue #264, #1483
> llm-faqgen: support air gapped environment

- comps/third_parties/nebula/deployment/docker_compose/docker-compose.yaml
- tests/third_parties/test_third_parties_nebula_docker.sh
Resolve nebula test error
https://github.com/opea-project/GenAIComps/issues/1591
- [x ] Bug fix (non-breaking change which fixes an issue)
> Fix nebula docker compose errors

- comps/agent/src/integrations/strategy/react/planner.py
Fix for react due to langgraph api change.
`n/a`.
> Fix for react due to langgraph api change

- .github/workflows/pr-examples-test.yml
- comps/third_parties/nginx/deployment/docker_compose/start-nginx.sh
use sh instead of bash for nginx entrypoint
https://github.com/opea-project/GenAIExamples/issues/2078
https://github.com/opea-project/GenAIExamples/issues/2079
https://github.com/opea-project/GenAIExamples/actions/runs/15700726719
> use sh instead of bash for nginx entrypoint

- .github/workflows/scripts/codeScan/.hadolint.yaml
- comps/dataprep/src/Dockerfile.openEuler
Fix the dockerfile hadolint scan issue
> fix the dockerfile hadolint scan issue

- .github/workflows/push-infra-issue-creation.yml
> use upstream action tool

- comps/chathistory/src/Dockerfile
- comps/feedback_management/src/Dockerfile
Remove libgl1-mesa-glx from Dockerfiles cont.
https://github.com/opea-project/GenAIComps/issues/1781
> Remove libgl1-mesa-glx from Dockerfiles cont.

- comps/asr/deployment/docker_compose/README.md
- comps/asr/src/README.md
> Refine document for asr

- comps/dataprep/src/integrations/elasticsearch.py
- comps/dataprep/src/integrations/vdms.py
Fix dataprep ingest issues.
Fixes https://github.com/opea-project/GenAIComps/issues/1368
Fixes https://github.com/opea-project/GenAIComps/issues/1369
None
Local tested
> Fix Dataprep Issues

- .github/workflows/push-infra-issue-creation.yml
Change default owner to Sakari of automatically created issues in GenAIInfra.
`n/a`.
> Change default owner of automatically created issue

- comps/third_parties/wav2lip/src/Dockerfile.intel_hpu
- tests/animation/test_animation_wav2lip_on_intel_hpu.sh
Fix wav2lip  ffmpeg issue
Fixes https://github.com/opea-project/GenAIComps/issues/1780
official version of ffmpeg
CI test
> Fix wav2lip ffmpeg issue

- comps/dataprep/deployment/kubernetes/qdrant-values.yaml
- comps/third_parties/tei/deployment/kubernetes/gaudi-values.yaml
Sync helm charts values with GenAIInfra for v1.4 release
> Sync helm charts values with GenAIInfra

- comps/version.py
> bump version into v1.4

- .github/workflows/push-base-image-upstream.yml
Update base image on push release for comps-base-openeuler 
> Update base image on push release

- comps/retrievers/src/requirements-cpu.txt
- comps/retrievers/src/requirements-gpu.txt
- comps/retrievers/src/requirements.in
Fix retrievers CVE
https://github.com/opea-project/GenAIComps/issues/1870
> Fix retrievers CVE

- comps/text2cypher/src/Dockerfile.intel_hpu
Limit optimum-habana==1.17.0 to fix import error.
https://github.com/opea-project/GenAIExamples/issues/2222
https://github.com/opea-project/GenAIExamples/actions/runs/17262324058
>  Limit optimum-habana==1.17.0 to fix import error.
