GenAIComps/mega/async_loop.py, GenAIComps/mega/base_service.py, GenAIComps/mega/logger.py, GenAIComps/mega/service.py, GenAIComps/mega/utils.py
The framework and base class for microservices.
Start an HTTP (fastapi) service using async loop. User could customize microservice based on HTTPService class.
Tested on local server.
```
from async_loop import AsyncLoop
args = {
'name': 'test_loop',
'cors': False,
'protocol': 'http',
'port': 8080,
'host': 'localhost',
'runtime_args': {        
'title': 'test_service',
'description': "this is a test."
}
}
loop = AsyncLoop(args)
with loop:
loop.run_forever()
```
=> Add HTTPService and AsyncLoop for microservice

GenAIComps/llms/vllm/README.md, GenAIComps/scheduler/dag.py, GenAIComps/scheduler/mega_service.yaml, GenAIComps/scheduler/s1.py, GenAIComps/scheduler/s2.py, GenAIComps/scheduler/s3.py, GenAIComps/scheduler/s4.py, GenAIComps/scheduler/s5.py, GenAIComps/scheduler/service_builder.py, GenAIComps/scheduler/yaml_service_builder.py
feature
Microservices dataflow is organized in a DAG, we expose two ways: Python API or Yaml config to define that. Further features are to be done including Ingress/Egress, megaservice API etc.
usage e.g.
Yaml
```
- (s1, s5) >> s2
- s2 >> (s3, s4)
- s3 >> s4
```
equivalent to
Python
```
service_builder = ServiceBuilder(port=1234, hostfile=None)
s1 = BaseService(id="s1", endpoint="http://localhost:8081/v1/add")
s2 = BaseService(id="s2", endpoint="http://localhost:8082/v1/add")
s3 = BaseService(id="s3", endpoint="http://localhost:8083/v1/add")
s4 = BaseService(id="s4", endpoint="http://localhost:8084/v1/add")
s5 = BaseService(id="s5", endpoint="http://localhost:8085/v1/add")
service_builder.add(s1).add(s2).add(s3).add(s4).add(s5)
service_builder.flow_to(s1, s2)
service_builder.flow_to(s5, …
```
=> Add DAG flow

comps/embeddings/README.md, comps/embeddings/docker/Dockerfile, comps/embeddings/docker/docker_compose_embedding.yaml, comps/embeddings/langchain/embedding_tei_gaudi.py, comps/embeddings/langchain/requirements.txt, comps/proto/docarray.py
Docker and Readme.
Add docker & readme for Embedding Microservice.
Fix minor bugs of embedding service.
Embedding service can be started using docker (manually or docker compose).
Add dependendies in requirements.txt
=> Add docker & readme for Embedding Microservice

comps/llms/README.md, comps/llms/langchain/docker/Dockerfile, comps/llms/langchain/docker/docker_compose_llm.yaml, comps/llms/langchain/llm_tgi.py, comps/llms/requirements.txt
Dockerfile and README
Add dockerfile and README for LLM Microservice.
Add requirements.
LLM service can be started using docker (manually or docker compose).
Add dependendies in requirements.txt
=> Add docker and readme for LLM Microservice

comps/llms/langchain/docker/Dockerfile
Bug fix: Dockerfile (`comps/llms/langchain/docker/Dockerfile`) referenced file that does not exist (`comps/cores/telemetry/requirements.txt`).  This file was removed in following commit: 
[migrate all the ut cases under cores and fix bug (](https://github.com/opea-project/GenAIComps/commit/a9399ed8579778f8aebfb01794d992b193791c0a)https://github.com/opea-project/GenAIComps/pull/47[)](https://github.com/opea-project/GenAIComps/commit/a9399ed8579778f8aebfb01794d992b193791c0a) by @chensuyue.
Following Docker build would error.
```
docker build -t opea/gen-ai-comps:llm-tgi-server --build-arg https_proxy=$https_proxy --build-arg http_proxy=$http_proxy -f comps/llms/langchain/docker/Dockerfile .
```
Docker build now passes:
```
docker build -t opea/gen-ai-comps:llm-tgi-server --build-arg …
```
=>  Bug fix LLM Dockerfile would not build

comps/retrievers/langchain/retriever_redis.py
The ingestion and `redis` retriever should use the same embedding model. It seems that the ingestion decides the embedding model based on environment variable `TEI_EMBEDDING_ENDPOINT`, but `redis` retriever use a hardcode model named `BAAI/bge-base-en-v1.5`.  This PR makes them consistent.
I run the test in my local K8s cluster.
=> The embedding model should be consistent for microservice retriever

comps/cores/mega/orchestrator.py, comps/llms/langchain/llm_tgi.py
Fix the stream forwarding issue between LLM and Megaservice gateway.
Two root causes:
1. HuggingFaceEndpoint.stream
- `llm.stream` doesn't work in streaming way, need to use `llm.atream` instead
- Need to modify the generator into asynchronous function.
2. SSE Protocol
- response.iter_lines()
- **delimiter=b"\0"**：Recognizes a stream of bytes as a whole chunk and returns it in one shot.
- **delimiter=None**: The default use of “\n” incorrectly cuts the byte stream, resulting in the absence of the required end identifier “\n\n” in the yield format.
- response.iter_content()
- **chunk_size=None**：If stream=True, it will not cut the byte stream twice, and output the byte according to the received byte size directly; if stream=False, it will cut the byte stream with chunk_size=1.
- …
=> Fix Stream Forwarding Issue

comps/dataprep/redis/README.md, comps/dataprep/redis/docker/docker-compose-dataprep-redis.yaml, comps/dataprep/redis/prepare_doc_redis.py, comps/dataprep/redis/requirements.txt, comps/embeddings/README.md, comps/embeddings/langchain/docker/docker_compose_embedding.yaml, comps/embeddings/langchain/embedding_tei_gaudi.py, comps/embeddings/langchain/requirements.txt, comps/guardrails/README.md, comps/guardrails/langchain/docker/docker_compose_guardrails.yaml, comps/guardrails/langchain/guardrails_tgi_gaudi.py, comps/guardrails/requirements.txt, comps/llms/README.md, comps/llms/summarization/tgi/docker_compose_llm.yaml, comps/llms/summarization/tgi/llm.py, comps/llms/summarization/tgi/requirements.txt, comps/llms/text-generation/tgi/docker_compose_llm.yaml, comps/llms/text-generation/tgi/llm.py, comps/llms/text-generation/tgi/requirements.txt, comps/reranks/README.md, comps/reranks/langchain/docker/docker_compose_reranking.yaml, comps/reranks/langchain/local_reranking.py, comps/reranks/langchain/reranking_tei_xeon.py, comps/reranks/requirements.txt, comps/retrievers/README.md, comps/retrievers/langchain/docker/docker_compose_retriever.yaml, comps/retrievers/langchain/retriever_redis.py, comps/retrievers/requirements.txt
Enable Benchmark with Langsmith.
Users are able to monitor latency and thoughput of each microservices on Langsmith.
n/a
Add `langsmith` in each `requirements.txt` files.
=> Enable Benchmark with Langsmith

README.md, comps/reranks/README.md, comps/retrievers/README.md
Update retrieve and reranking README
=> Update retrieve and reranking README.md

comps/llms/README.md
Validate new LLM model(LLaMA3 8B, Phi 3, LLaMA3 70B) run on TGI-Gaudi 
`n/a`
No newly introduced 3rd party dependency.
LLaMA3 8B
Phi 3
LLaMA3 70B
=> Llama3 and phi3  validation result update.

comps/guardrails/README.md
This makes two small changes to guardrails README.md:
- Changes to correct parameter of /v1/guardrails API call
- Add `-e no_proxy` to docker run since API calls to model inference service may be sent to proxy otherwise
`n/a`.
Documentation change
=> Documentation fix: fix api call parameter and added no proxy

comps/llms/text-generation/tgi/llm.py
Update LLM microservice output to binary to adapt frontend format.
The output format of `all related examples` using LLM microservice will be changed.
n/a
None
Local tested & integration tested with frontend.
=> Update LLM microservice output to binary

comps/cores/mega/gateway.py
Fix stream=false doesn't work issue
n/a
None
Local tested on Gaudi2
=> Fix stream=false doesn't work issue

README.md, comps/cores/mega/gateway.py, comps/cores/mega/orchestrator.py, requirements.txt, tests/cores/mega/test_aio.py, tests/cores/mega/test_service_orchestrator.py, tests/cores/mega/test_service_orchestrator_with_gateway.py
This PR
* allow subsequent requests to be handled non-blocking in earlier microservices concurrently
* allow microservices on DAG branches to be handled concurrently
n/a
aiohttp
add a local test
also with GenAIEval, evals/benchmark/chatqna_benchmark.py
The  data shows a ~1.5x speedup for P99 latency with total concurrent number of requests: 2,4,8,16,32,64
=> Add aio orchestrator to boost concurrent serving

README.md
This PR mainly updates the table of main readme by adding vllm-cpu/ray-cpu/ray gaudi llm service.
`n/a`.
- just updated the main readme tables where llms support vllm-cpu and ray-cpu and ray-gaudi.
N/A.
This PR is validated through the previous [#79](https://github.com/opea-project/GenAIComps/pull/79).
=> Refine the main readme by adding vllm/ray llm service

comps/__init__.py, comps/cores/mega/gateway.py
Add translation gateway class
`n/a`
`n/a`
`n/a`
=> Add Gateway for Translation

comps/cores/proto/docarray.py, comps/dataprep/milvus/README.md, comps/dataprep/milvus/prepare_doc_milvus.py, comps/dataprep/qdrant/README.md, comps/dataprep/qdrant/prepare_doc_qdrant.py, comps/dataprep/redis/README.md, comps/dataprep/redis/langchain/prepare_doc_redis.py, comps/retrievers/langchain/milvus/README.md, comps/retrievers/langchain/milvus/retriever_milvus.py, comps/retrievers/langchain/redis/README.md, comps/retrievers/langchain/redis/retriever_redis.py
Use parameter for retriever
n/a.
Pass
=> Use parameter for retriever

comps/reranks/langchain-mosec/README.md, comps/reranks/langchain-mosec/__init__.py, comps/reranks/langchain-mosec/docker/Dockerfile, comps/reranks/langchain-mosec/docker/docker_compose_embedding.yaml, comps/reranks/langchain-mosec/mosec-docker/Dockerfile, comps/reranks/langchain-mosec/mosec-docker/server-ipex.py, comps/reranks/langchain-mosec/requirements.txt, comps/reranks/langchain-mosec/reranking_mosec_xeon.py, tests/test_reranks_langchain-mosec.sh
Add a new reranking based on mosec.
`n/a`.
- [ *] New feature (non-breaking change which adds new functionality)
mosec
ipex
see the new added test script: tests/test_embeddings_langchain-mosec.sh
=> Add a new reranking based on mosec.

tests/cores/mega/test_base_statistics.py
=> statistics ut coverage

comps/llms/text-generation/vllm/docker/Dockerfile.microservice
This PR adds optional `build-arg`'s for this Dockerfile: comps/llms/text-generation/vllm/docker/Dockerfile.microservice
Current dockerfile always defaults to `gpu` Torch installation while `CPU` users might not necessarily need extra packages.
This leads to smaller containers for CPU users and faster build.
For users interested to do `gpu` builds all they need to do is build this image this way:
```
docker build --build-arg ARCH='gpu' -f comps/llms/text-generation/vllm/docker/Dockerfile.microservice . -t opea/llm-vllm:latest
```
- extra `build-arg` option `ARCH` to build `vllm microservice` container for either CPU or GPU.
None
=> optional vllm microservice container build

comps/retrievers/langchain/redis/README.md, comps/retrievers/langchain/redis/docker/Dockerfile, comps/retrievers/langchain/redis/retriever_redis.py, comps/retrievers/langchain/redis/run.sh, tests/test_retrievers_langchain_redis.sh
Remove ingest in Retriever microservice and support similarity search in empty Redis vector db.
n/a
None
Local test and CI test.
=> Remove ingest in Retriever MS

comps/guardrails/pii_detection/docker/Dockerfile, comps/knowledgegraphs/langchain/docker/Dockerfile, comps/web_retrievers/langchain/chroma/docker/Dockerfile
This PR adds optional `build-arg`'s for the following Dockerfiles:
```
- comps/guardrails/pii_detection/docker/Dockerfile
- comps/knowledgegraphs/langchain/docker/Dockerfile
- comps/web_retrievers/langchain/chroma/docker/Dockerfile
```
Current Dockerfiles always defaults to `gpu` Torch installation while `CPU` users might not necessarily need extra packages. This had the advantage of building smaller containers for CPU users and faster builds.
For users interested to do `gpu` builds, all they need to do is build this image this way for example:
```
docker build --build-arg ARCH='gpu' -f comps/guardrails/pii_detection/docker/Dockerfile . -t opea/guardrails-pii-detection:latest
```
- extra `build-arg` option …
=> Architecture specific args for a few containers

comps/embeddings/langchain-mosec/mosec-docker/server-ipex.py
Difference embedding model may have different input arguments.
This patch adaptively detect model arguments.
`n/a`
- [*] Bug fix (non-breaking change which fixes an issue)
'n/a'.
Use EMB_MODEL environ to switch to different embedding models.
Bge-large-zh and bce-embedding-base-v1 is tested locally.
=> embeddings: adaptive detect embedding model arguments in mosec

comps/cores/mega/orchestrator.py
Enlarge megaservice request timeout for supporting high concurrency
`n/a`
- [ x ] Bug fix (non-breaking change which fixes an issue)
None
Local test and pre-CI test.
=> Enlarge megaservice request timeout for supporting high concurrency

comps/asr/Dockerfile, comps/dataprep/milvus/docker/Dockerfile, comps/dataprep/pgvector/langchain/docker/Dockerfile, comps/dataprep/pinecone/docker/Dockerfile, comps/dataprep/qdrant/docker/Dockerfile, comps/dataprep/redis/langchain/docker/Dockerfile, comps/dataprep/redis/langchain_ray/docker/Dockerfile, comps/dataprep/redis/llama_index/docker/Dockerfile, comps/guardrails/langchain/docker/Dockerfile, comps/guardrails/pii_detection/docker/Dockerfile, comps/llms/utils/lm-eval/Dockerfile.cpu, comps/reranks/fastrag/docker/Dockerfile, comps/reranks/tei/docker/Dockerfile, comps/retrievers/langchain/milvus/docker/Dockerfile, comps/tts/Dockerfile
Update Dockerfiles to fix syntax warning when building files
https://github.com/opea-project/GenAIComps/issues/326
- [X ] Bug fix (non-breaking change which fixes an issue)
None
Build all Dockerfiles locally using docker on Ubuntu 22.04.4.
=> Update to remove warnings when building Dockerfiles due to unsafe syntax

comps/dataprep/milvus/prepare_doc_milvus.py, tests/test_dataprep_milvus.sh
Support delete for Milvus vector db in Dataprep.
new apis:
- /v1/dataprep/get_file
- /v1/dataprep/delete_file
UT `test_dataprep_milvus.sh` added
n/a
None
Local tested with Python, Docker and e2e test script.
=> Support delete for Milvus vector db in Dataprep

comps/dataprep/redis/langchain/prepare_doc_redis.py, comps/dataprep/redis/langchain/requirements.txt, tests/test_dataprep_redis_langchain.sh
Refine Dataprep Code & UT
block the e2e CI test of https://github.com/opea-project/GenAIExamples/pull/486.
None
Local tested the test script.
=> Refine Dataprep Code & UT

comps/embeddings/langchain-mosec/README.md, comps/embeddings/langchain-mosec/mosec-docker/server-ipex.py
[Enhence] Increate mosec_embedding forward timeout to support high concurrency cases
ref: 
* https://mosecorg.github.io/mosec/reference/interface.html
* https://github.com/mosecorg/mosec/pull/321
* https://github.com/mosecorg/mosec/issues/298
avoid timeout issues if high concurrency.
N/A
=> [Enhence] Increase mosec_embedding forward timeout to support high concurrency cases

comps/cores/mega/micro_service.py, comps/dataprep/redis/README.md, comps/dataprep/redis/langchain/prepare_doc_redis.py, tests/test_dataprep_redis_langchain.sh
use same port number with different route in one microservice
todo:
1. refine other comps by related owners
2. refine examples, update dataprep-redis related config, see [this pr](https://github.com/opea-project/GenAIExamples/pull/557)
=> unify port in one microservice.

comps/embeddings/langchain-mosec/README.md, comps/reranks/langchain-mosec/README.md, tests/test_embeddings_langchain-mosec.sh, tests/test_reranks_langchain-mosec.sh
Modify the docker image name of embedding and reranking, normalized with prefix "opea/".
`n/a`.
- [*] Others (enhancement, documentation, validation, etc.)
N/A.
N/A.
=> [tests] normalize embedding and reranking endpoint docker image name

comps/dataprep/milvus/config.py
Fix hardcode part in config.py of dataprep code
n/a
n/a
local test
=> Update dataprep default mosec embedding model in config.py

comps/cores/mega/gateway.py, comps/dataprep/milvus/config.py, comps/lvms/lvm_tgi.py, requirements.txt
Support multiple image sources for LVM microservice: 
(1) Image URL
(2) Local image path
(3) Image Base64 string
`n/a`
None
Local test and pre-CI test.
=> Support multiple image sources for LVM microservice

comps/llms/text-generation/ollama/llm.py
vLLM and oLLAMa get the model name from the envrionment
=> LLM micro service input data does not have input model name

.github/workflows/pr-microservice-test.yml, tests/test_asr.sh, tests/test_tts.sh
Clean test images before test
To avoid issue like this case, the image build failed, but test still pass due to the local exist images from other test.  
=> clean local images before test

comps/retrievers/haystack/qdrant/README.md
* Refine readme structure
* Remove repeated env variable for bare metal execution
* Add env vars settings of tei/qdrant port and align with the name while launching the docker container
Fix the issue reported in: https://github.com/opea-project/GenAIComps/issues/360
N/A
[Consume Retriever Service](https://github.com/opea-project/GenAIComps/tree/main/comps/retrievers/haystack/qdrant#3-consume-retriever-service)
=> Refine the instructions to run the retriever example with qdrant

comps/embeddings/llama_index/local_embedding.py, comps/embeddings/llama_index/requirements.txt
HuggingFaceEmbeddings is deprecated in favor of 'HuggingFaceInferenceAPIEmbedding'
https://github.com/run-llama/llama_index/blob/1abbc5a8eb5135eb695138caebfb573f7a10e5d3/llama-index-integrations/embeddings/llama-index-embeddings-huggingface/llama_index/embeddings/huggingface/base.py#L279
llama-index-embeddings-huggingface-api
=> fix HuggingFaceEmbedding deprecated in favor of HuggingFaceInferenceAPIEmbedding

comps/guardrails/llama_guard/README.md, comps/guardrails/llama_guard/guardrails_tgi.py, comps/guardrails/llama_guard/requirements.txt, tests/test_guardrails_llama_guard.sh
This PR attempts to reduce latency by allowing safeguard microservice to be at end of DAG and process safety of both input and output with single query. This means you can structure the DAG as follows to reduce latency of RAG flow:
```python
self.megaservice.add(embedding).add(retriever).add(rerank).add(llm).add(guardrails)
self.megaservice.flow_to(embedding, retriever)
self.megaservice.flow_to(retriever, rerank)
self.megaservice.flow_to(rerank, llm)
self.megaservice.flow_to(llm, guardrails)
self.gateway = ChatQnAGateway(megaservice=self.megaservice, host="0.0.0.0", port=self.port)
```       
Currently our implementation only supports single input safeguarding. But the chat Messages API (`v1/chat/completion`) will allow for templating for both "user" inputs and "assistant" output. with a …
=> Add output evaluation for guardrails

comps/cores/proto/api_protocol.py
Revert the default value of  max_new_tokens to 1024
n/a`
None.
Local test.
=> Revert the default value of  max_new_tokens to 1024

comps/retrievers/haystack/qdrant/retriever_qdrant.py
Fix Retriever qdrant issue.
Return `[]` for empty retrieved docs.
The CI failed [here](https://github.com/opea-project/GenAIExamples/pull/569) for ChatQnA qdrant.
None
CI test
=> Fix Retriever qdrant issue

comps/asr/whisper/whisper_model.py
Default input audio should not be padded otherwise will recognize nothing rather than "you". This is related to GenAIExamples UT.
na
None
Local test
=> fix asr ut on hpu

.github/workflows/pr-examples-test.yml
adapt GenAIExample test structure refine
https://github.com/opea-project/GenAIComps/actions/runs/10417698619/job/28852439035?pr=505
=> adapt GenAIExample test structure refine

comps/vectorstores/langchain/chroma/README.md
This file use ```log  but there's no such syntax highlight language. Leave it empty instead.
=> doc: remove use of unknown highlight language

comps/llms/text-generation/ollama/README.md
* Add commands to restart the ollama service. Otherwise, the proxy setting in the ollama.service file will not take effect before pulling the model with ollama.
* Add proxy settings while launching the opea-ollama docker container.
Found issues while verifying the ollama example during supporting the issue reported in https://github.com/opea-project/GenAIComps/issues/367. 
N/A
Ollama example on llama3.
=> Add cmds to restart ollama service and add proxy settings while launching docker

comps/tts/speecht5/speecht5_model.py
Revise TTS microservice,  by configging `split_long_text_into_batch` function of the `SpeechT5Model` to end the last audio chunk at the correct punctuation mark location and discard parts that will break sentence continuity
n/a
N/A
```
User Query: tell us about inflation in the us in the past few years
AI Answer: Inflation in the United States over the past few years has been relatively low and stable. According to the U.S. Bureau of Labor Statistics, the Consumer Price Index (CPI) measures the change in prices for a fixed basket of goods and services purchased by consumers. The CPI is a
```
In the above test case, the revised version of TTS will not include "The CPI is a" in the last audio chunk and end at …
=> Revise TTS, SpeechT5Model to end the last audio chunk at the correct punctuation mark location

comps/__init__.py, comps/cores/mega/constants.py, comps/cores/mega/gateway.py
Add a new gateway which returns searched docs
`n/a`.
- [x ] New feature (non-breaking change which adds new functionality)
No
TBD
=> Add Retrieval gateway in core to support IndexRetrivel Megaservice

.github/workflows/scripts/freeze_images.sh, comps/llms/text-generation/native/docker/Dockerfile, comps/llms/text-generation/vllm-ray/docker/Dockerfile.vllmray, comps/llms/text-generation/vllm/docker/Dockerfile.hpu
This PR proposes using `vault.habana.ai/gaudi-docker/1.16.1/ubuntu22.04/habanalabs/pytorch-installer-2.2.2:latest` across the board.
N/A
- [N/A] Bug fix (non-breaking change which fixes an issue)
- [N/A] New feature (non-breaking change which adds new functionality)
- [N/A] Breaking change (fix or feature that would break existing design and interface)
None.
This change won't affect CIs.
=> Using habana docker 1.16.1 everywhere

comps/agent/langchain/agent.py, comps/agent/langchain/requirements.txt, comps/agent/langchain/src/agent.py, comps/agent/langchain/src/global_var.py, comps/agent/langchain/src/strategy/base_agent.py, comps/agent/langchain/src/strategy/planexec/planner.py, comps/agent/langchain/src/strategy/ragagent/planner.py, comps/agent/langchain/src/strategy/react/planner.py, comps/agent/langchain/src/thread.py, comps/agent/langchain/test.py, comps/agent/langchain/test_assistant_api.py, comps/cores/proto/api_protocol.py, tests/test_agent_langchain.sh
Add Assistant API for agent
https://github.com/opea-project/GenAIComps/issues/365
No
test_agent_langchain.sh
=> Add Assistant API for agent

.github/workflows/scripts/freeze_images.sh
Update reg for dockerfile
`n/a`
`n/a`
`n/a`
=> fix freeze workflow

comps/llms/text-generation/tgi/README.md, comps/llms/text-generation/tgi/docker_compose_llm.yaml, comps/llms/text-generation/tgi/llm.py
Support no_rerank input for LLM.
Add input type `SearchedDoc`.
ChatQnA pipeline is able to run without `Rerank` Microservice now.
n/a
None
Local tested llm microservice and ChatQnA pipeline.
=> Support SearchedDoc input type in LLM for No Rerank Pipeline

comps/embeddings/langchain/local_embedding_768.py
Add a new local_embedding file which returns 768 embedding length instead of 1024 and use BAAI/bge-base-en-v1.5
the local_embedding return and redis_retriever is not compatible at this moment.  
No
No
=> Add local_embedding return 768 length to align with chatqna example

.github/workflows/docker/compose/tts-compose.yaml, comps/cores/telemetry/README.md
add telemetry doc
na
None
None
=> add telemetry doc

comps/llms/text-generation/vllm-ray/requirements.txt
`langserve` was previously removed from all `requirements.txt` files and was added to `requirements-runtime.txt`.
If there's still a need for that, it can be installed at runtime.
But looking at this `comps/llms/text-generation/vllm-ray/docker/Dockerfile.microservice` there's no `CMD` or `ENTRYPOINT` to begin with.
That means the dependency may not even be needed.
N/A
- [Y] Bug fix (non-breaking change which fixes an issue)
- [N] New feature (non-breaking change which adds new functionality)
- [N] Breaking change (fix or feature that would break existing design and interface)
- [N] Others (enhancement, documentation, validation, etc.)
None
TBD
=> Remove redundant dependency from 'vllm-ray' comps

comps/guardrails/README.md, comps/guardrails/toxicity_detection/README.md
This is just a documentation PR to fix typos and add definitions for toxicity detection microservice.
`n/a`.
Just docs changes
=> Fix typos and add definitions for toxicity detection microservice

comps/agent/langchain/README.md, comps/cores/telemetry/README.md, comps/dataprep/redis/README.md, comps/dataprep/redis/multimodal_langchain/README.md, comps/embeddings/neural-speed/README.md, comps/feedback_management/mongo/README.md, comps/finetuning/README.md, comps/guardrails/toxicity_detection/README.md, comps/intent_detection/README.md, comps/llms/text-generation/ollama/README.md, comps/llms/text-generation/vllm-openvino/README.md, comps/lvms/video-llama/README.md, comps/prompt_registry/mongo/README.md, comps/reranks/video-rag-qna/README.md, comps/retrievers/langchain/README.md, comps/retrievers/langchain/vdms/README.md, comps/vectorstores/README.md
* only one H1 (#) heading for the title is allowed, so fix the extra H1 headings (and the subheadings under those) to appropriate levels
* fix some inline code blocks containing leading/trailing spaces
* fix some indenting issues under an ordered list item
=> doc: fix heading levels in markdown content

.github/workflows/_comps-workflow.yml, .github/workflows/docker/compose/lvms-compose-cd.yaml, tests/test_lvms_tgi_llava_next.sh
- This PR switches from personal forks to upstream repo and if needed makes adjustments as a patch
- It als eliminates building the container `opea/llava-tgi:comps` from scratch during testing and instead uses the prebuilt container: `ghcr.io/huggingface/tgi-gaudi:2.0.4`
N/A
- [N] Bug fix (non-breaking change which fixes an issue)
- [N] New feature (non-breaking change which adds new functionality)
- [N] Breaking change (fix or feature that would break existing design and interface)
- [Y] Others (enhancement, documentation, validation, etc.)
None
There's a CI for this
=> switch to using upstream 'tgi-gaudi' on HuggingFace

comps/finetuning/README.md, comps/finetuning/finetune_config.py, comps/finetuning/llm_on_ray/finetune/data_process.py, comps/finetuning/llm_on_ray/finetune/finetune.py, comps/finetuning/llm_on_ray/finetune/modeling.py, tests/test_finetuning_embedding_hpu.sh
1. embedding finetuning on cpu/gaudi2/gpu
2. add ut
3. update readme
=> enable embedding finetuning

README.md, comps/dataprep/redis/README.md, comps/dataprep/redis/langchain/config.py, comps/embeddings/README.md, comps/embeddings/langchain/local_embedding.py, comps/embeddings/llama_index/embedding_tei.py, comps/embeddings/llama_index/local_embedding.py, comps/reranks/README.md, comps/reranks/langchain-mosec/mosec-docker/Dockerfile, comps/reranks/tei/local_reranking.py, tests/test_embeddings_langchain-mosec.sh, tests/test_embeddings_langchain.sh, tests/test_embeddings_llama_index.sh, tests/test_reranks_langchain-mosec.sh, tests/test_reranks_tei.sh
unify default reranking model with BAAI/bge-reranker-base, align with GenAIExamples
=> unify default reranking model with BAAI/bge-reranker-base

comps/dataprep/utils.py
Fix the loading of jsonl file with line loading
Bug fix (non-breaking change which fixes an issue)
=> Fix the loading error of jsonl file

comps/embeddings/mosec/langchain/Dockerfile, comps/embeddings/multimodal/multimodal_langchain/Dockerfile, comps/embeddings/multimodal_clip/Dockerfile, comps/embeddings/tei/langchain/Dockerfile, comps/guardrails/llama_guard/langchain/Dockerfile, comps/guardrails/toxicity_detection/Dockerfile, comps/intent_detection/langchain/Dockerfile, comps/knowledgegraphs/langchain/Dockerfile, comps/llms/faq-generation/tgi/langchain/Dockerfile, comps/llms/summarization/tgi/langchain/Dockerfile, comps/llms/text-generation/ollama/langchain/Dockerfile, comps/llms/text-generation/tgi/Dockerfile, comps/llms/text-generation/vllm/langchain/Dockerfile, comps/llms/text-generation/vllm/ray/Dockerfile, comps/ragas/tgi/langchain/Dockerfile, comps/reranks/mosec/langchain/Dockerfile, comps/retrievers/multimodal/redis/langchain/Dockerfile, comps/retrievers/pathway/langchain/Dockerfile, comps/retrievers/pgvector/langchain/Dockerfile, comps/retrievers/pinecone/langchain/Dockerfile, comps/retrievers/redis/langchain/Dockerfile, comps/retrievers/vdms/langchain/Dockerfile, comps/web_retrievers/chroma/langchain/Dockerfile, tests/llms/test_llms_text-generation_tgi.sh, tests/retrievers/test_retrievers_pinecone_langchain.sh, tests/retrievers/test_retrievers_redis_langchain.sh
replace langchain/langchain:latest with python:3.11-slim
https://github.com/opea-project/GenAIComps/issues/543
=> replace langchain/langchain:latest with python:3.11-slim

comps/llms/text-generation/vllm/langchain/README.md, comps/llms/text-generation/vllm/langchain/llm.py, comps/llms/text-generation/vllm/langchain/template.py
Include SearchedDoc in /v1/chat/completions endpoint to accept document data retreived from retriever service to parse into LLM for answer generation.
- [*] New feature (non-breaking change which adds new functionality)
N/A
N/A
=> vllm langchain: Add Document Retriever Support

.github/workflows/_comps-workflow.yml, .github/workflows/_run-docker-compose.yml, .github/workflows/manual-comps-test.yml
=> update cd workflow

LEGAL_INFORMATION.md, README.md, comps/cores/telemetry/README.md, comps/nginx/README.md
Cross-repo references using an URL that only has the folder name cause links in the github.io site to go to the github.com site.  Most of these uses want to link to the documentation (README.md) so add that where appropriate so links in the github.io site stay there.
=> doc: fix missing references to README.md

comps/feedback_management/mongo/README.md, comps/prompt_registry/mongo/README.md, comps/prompt_registry/mongo/docker-compose-prompt-registry-mongo.yaml, comps/prompt_registry/mongo/prompt.py, tests/prompt_registry/test_prompt_registry_mongo.sh
6012, 6013, 6014 is used by chathistory.
6016 is used by feedback.
To avoid unnecessary confusion and conflict, change it to 6018.
`n/a`.
`n/a`.
No special test steps, just follow the README
=> change prompt usvc prot to 6018

comps/chathistory/mongo/README.md
After #449 , ports 6013/6014 are no longer needed, remove them from the docker run command.
=> Remove unused port reference

comps/dataprep/milvus/langchain/requirements.txt, comps/dataprep/neo4j/langchain/requirements.txt, comps/dataprep/pgvector/langchain/requirements.txt, comps/dataprep/pinecone/langchain/requirements.txt, comps/dataprep/qdrant/langchain/requirements.txt, comps/dataprep/redis/langchain/requirements.txt, comps/dataprep/redis/langchain_ray/requirements.txt, comps/dataprep/redis/llama_index/requirements.txt, comps/dataprep/utils.py, comps/dataprep/vdms/langchain/requirements.txt
File upload time too long according to feedback by customers.
Refine dataprep util with opencv and multithreading.
Time reduction:
- Load File: reduce by 70%~83%, depends on network and hardware
- Bottleneck of Save to DB: blocked by the performance of TEI service
n/a
Add `pytesseract` in requirements.txt.
Local tested.
- Time comsumption on Xeon:
| file size | origin | func1 | func2 | refined |
| -- | -- | -- | -- | -- |
| load document | 8.119s | 8.917s | 3.039s | 1.368s |
| save batch into db | 12.492s | 14.456s | 13.055s | 12.802s |
| total | 20.725s | 23.404s | 16.166s | 14.196s |
- Time comsumption on Gaudi:
| file size | origin | fun1 | func2 | refined |
| -- | -- | -- | -- | -- |
| load document | …
=> [Dataprep] Reduce Upload File Time Consumption

comps/reranks/mosec/langchain/dependency/server-ipex.py, comps/reranks/tei/local_reranking.py, comps/reranks/tei/reranking_tei.py
Remove unused python imports from reranks modules.
n/a
n/a
linting
=> Remove unused imports from reranks

comps/llms/text-generation/vllm/langchain/llm.py
This PR introduces fix for a issue identified while using `llm-vllm` microservice for RAG context retrieval.
ChatQnA application, when deployed with `llm-vllm` microservice to get inference from vLLM, was seen to be not able to provide answers based on documents being uploaded. This was the case despite merging PR #687, which was created to introduce this RAG capability for `llm-vllm` microservice.
Issue was fixed after minor updates in `llm.py`, to provide the generated RAG prompt as a parameter while invoking llm inferences.
NA : No New dependencies
Manual tests to validate retrieval from uploaded documents.
=> 🐛 bugfix : Retrieval on llm-vllm service not working

comps/asr/whisper/Dockerfile, comps/asr/whisper/dependency/Dockerfile, comps/dataprep/vdms/langchain/Dockerfile, comps/dataprep/vdms/multimodal_langchain/Dockerfile, comps/embeddings/multimodal_clip/Dockerfile, comps/image2video/dependency/Dockerfile, comps/llms/text-generation/vllm/langchain/dependency/Dockerfile.intel_hpu, comps/lvms/llama-vision/Dockerfile, comps/lvms/llama-vision/Dockerfile_guard, comps/lvms/llama-vision/Dockerfile_tp, comps/retrievers/multimodal/redis/langchain/Dockerfile, comps/retrievers/vdms/langchain/Dockerfile, comps/text2image/Dockerfile, tests/agent/Dockerfile.hpu, tests/embeddings/test_embeddings_tei_langchain.sh, tests/llms/test_llms_text-generation_tgi.sh
This PR ensures all `pip` installs have a `--no-cache-dir` option.
Installing `pip` packages without this option will store everything in `.cache` and leads to large containers that take longer to download.
None
CI test are sufficient.
=> add 'no-cache-dir' to all pip installs

.github/workflows/docker/ut.dockerfile, comps/dataprep/multimodal/redis/langchain/Dockerfile, comps/dataprep/vdms/langchain/Dockerfile, comps/dataprep/vdms/multimodal_langchain/Dockerfile, comps/embeddings/multimodal/multimodal_langchain/Dockerfile, comps/embeddings/multimodal_clip/Dockerfile, comps/intent_detection/langchain/Dockerfile, comps/retrievers/multimodal/redis/langchain/Dockerfile, comps/retrievers/pathway/langchain/Dockerfile, comps/retrievers/vdms/langchain/Dockerfile
This PR removes 'vim' from all Dockerfiles with the repo
Having unnecessary libraries leads to large containers that take longer to download
None
CI test are sufficient.
=> Remove 'vim' from Dockerfiles

comps/llms/text-generation/vllm/langchain/dependency/Dockerfile.intel_hpu, comps/llms/text-generation/vllm/llama_index/dependency/Dockerfile.intel_hpu, comps/llms/text-generation/vllm/ray/dependency/Dockerfile, comps/retrievers/neo4j/langchain/Dockerfile, comps/retrievers/vdms/langchain/Dockerfile, tests/agent/Dockerfile.hpu
This PR removes proxy definition from within Dockerfiles because they need to be provided by as `--env` when appropriate and otherwise left out in not needed.
Having unnecessary `ENV` vars to Dockerfiles is generally a bad practice.
None
CI test are sufficient.
=> Remove proxy definition from within Dockerfiles

.github/workflows/pr-dockerfile-path-scan.yaml
Possibly missing dollar sign in check script for hyperlinks in pr readmes
My pr https://github.com/opea-project/GenAIComps/pull/775 ran into error when checking hyperlinks in README.md, even after removing all "http" keywords
Reason may be the missing dollar sign for the "changed_files" variable.
n/a
n/a
=> missing dollar sign in check script for hyperlinks?

comps/dataprep/milvus/langchain/Dockerfile, comps/dataprep/milvus/langchain/README.md, comps/dataprep/milvus/langchain/config.py, comps/dataprep/milvus/langchain/prepare_doc_milvus.py, comps/embeddings/mosec/langchain/dependency/Dockerfile, comps/embeddings/mosec/langchain/dependency/server-ipex.py, comps/reranks/mosec/langchain/dependency/Dockerfile, comps/retrievers/milvus/langchain/config.py, comps/retrievers/milvus/langchain/retriever_milvus.py, tests/dataprep/test_dataprep_milvus_langchain.sh
Refactor the Milvus Dataprep and Retriever modules to enhance code readability and facilitate user-friendly configuration.
=> Refactor milvus dataprep and retriever

comps/cores/mega/orchestrator.py
When using GPT-SoVITS, it by default return `audio/wav` content which cannot be jsonlize. This is to support it.
na
None
UT
=> fix audio/wav response handling

comps/agent/langchain/src/tools.py
When using `pydantic` imports for `BaseModel, Field, create_model` (which is v2) in GenAIComps/comps/agent/langchain/src/tools.py file, LLM generates incorrect tool arg types for `dict[str, str]` schema type. Changing to use imports from `pydantic.v1` generates correct schema. Possibly due to `ChatOpenAI` using pydantic.v1.
Is it possible to change to use `pydantic.v1` in this file?
`n/a`
Using `BaseModel, Field, create_model` imports from pydantic:
Observed pydantic validation errors before entering tool.
Using `BaseModel, Field, create_model` imports from pydantic.v1:
Observe `params` to print as str type.
=> Fix llm not recognizing pydantic tool definition for dict types

comps/nginx/nginx.conf.template
Update Nginx default setting
Nginx default file size is 1MB, change to 10GB.
Upload 2MB files successfully.
It failed to upload the 2MB file without this PR.
=> Update Nginx default set

comps/web_retrievers/chroma/langchain/retriever_chroma.py
Fix web_retriever batch size issue.
The `Chroma.add_documents` function has the batch_size limitation of 32.
This PR limit the batch size of documents when adding documents into db.
n/a
None
Local tested.
=> Fix web_retriever batch size issue

comps/retrievers/pinecone/langchain/Dockerfile, comps/retrievers/pinecone/langchain/requirements.txt, comps/retrievers/pinecone/langchain/retriever_pinecone.py, tests/retrievers/test_retrievers_pinecone_langchain.sh, tests/utils/wait-for-it.sh
The Pinecone retriever was broken. It needed to create an Index for the retriever.
Note that Pinecone currently requires the use of a [cloud hosted Index](https://docs.pinecone.io/guides/indexes/understanding-indexes#cloud-regions). 
This seems potentially problematic for CI to depend on an external hosting service and at an API Key [limited rate](https://www.pinecone.io/pricing/).
#809 
WaitForIt 
- helper script to improve on guessed sleep times. 
- https://github.com/vishnubob/wait-for-it
Pinecone Index service hosted on AWS
Included CI test. Ran manually locally and through automated CI.
=> Pinecone retriever index fix

comps/cores/mega/utils.py, comps/embeddings/tei/langchain/embedding_tei.py, comps/llms/faq-generation/tgi/langchain/llm.py, comps/llms/summarization/tgi/langchain/llm.py, comps/llms/text-generation/tgi/llm.py, comps/reranks/tei/reranking_tei.py
To support remote TGI/TEI endpoints instead of running it locally along with if these endpoints are protected with OAuth Client Credentials flow.
n/a
Added get_access_token method in utils.py to get the OAuth Client Credentials flow by taking parameters clientid, clientsecret and tokenurl from environment variables. Using utils.py so that the fucntion can be reused in multiple places.
Added authentication i.e Authorization header to pass the token in multiple components like embedding, llm-faqgen, llm-sumarization, llm-text-generation and reranking files. These components uses the common get_access_token method from utils.
Describe the tests that you …
=> Remote TGI/TGI services with OAuth Client Credentials authentication

comps/tts/gpt-sovits/Dockerfile
Make gpt-sovits to run as normal user as all other opea container images.
#838
=> gpt-sovits: Run as normal user

comps/web_retrievers/chroma/langchain/retriever_chroma.py
enable parameter k to get web resources of num k.
By default, web retriever gets only one web resource, which will cause the empty result if any exception occurs.
None
Local tested
=> Enable Parameter k for Web Retriever

comps/cores/mega/base_statistics.py, comps/cores/mega/gateway.py, comps/cores/mega/http_service.py, comps/cores/mega/micro_service.py, comps/cores/mega/orchestrator.py, tests/cores/mega/test_service_orchestrator_streaming.py
PR does following changes:
* Adds request, first token and inter-token latency Prometheus metrics, for monitoring application performance
* To ServiceOrchectrator token processing, which seems only place where this could be done
* Adds "inprogress" HTTP metrics that can be used for scaling application uservices based on incoming requests
* Needed because currently provided number of already processed HTTP requests tells just how much of them service currently *can* process, not how many additional ones it should be able to process
* Fixes BaseStatistics method name typos
https://github.com/opea-project/GenAIExamples/issues/391
No new ones.
(`prometheus_fastapi_instrumentator` imported for `HttpService` …
=> Add E2E Promeheus metrics to applications

comps/cores/mega/http_service.py
Minor fix to https://github.com/opea-project/GenAIComps/pull/845
follow Underscore format that prometheus accepts
ValueError: Invalid metric name: http_requests_inprogress_comps-chat-agent
na
na
=> fix prometheus invalid metric name

comps/dataprep/redis/langchain/prepare_doc_redis.py
Fix the delete file bug when the container is restarted.
n/a
None
Local tested
=> [Dataprep] Fix Delete Bug

comps/cores/mega/http_service.py, comps/cores/mega/orchestrator.py, comps/cores/telemetry/README.md
This new metric matches better the earlier added (LLM usage specific) request latency one, and does _not_ have the issues that the `inprogress` metric for `prometheus-fastapi-instrumentator`  in `HttpService` did:
* Create extra instances which have to be differentiated e.g. for CI:
* See: https://github.com/opea-project/GenAIComps/pull/845#issuecomment-2452219683
* Rely on metric instance (name) differentiator coming through obscure kwargs call-chain:
* `name` => `Gateway` => `MicroService` => `HttpService` => `BaseService` => `HttpService.title`
* Create separate `inprogress` metrics also for metric and health queries
I.e. it does not create useless extra metrics, and it's a bit easier to reason how & why it works.
(This reverts the "inprogress" metric part of commit …
=> Replace HTTP "inprogress" gauge with megaservice "request_pending" one

tests/agent/test_agent_langchain_on_intel_hpu.sh
Standardize the naming format of images.
=> Standardize the naming format of images

comps/agent/langchain/src/strategy/react/planner.py, comps/agent/langchain/src/strategy/react/utils.py
define a new func to get agent history from memory
=> fix history content from agent memory.

comps/dataprep/multimodal/redis/langchain/multimodal_utils.py
Fixes a bug in the `dataprep-multimodal-redis` microservice where non-zero time metadata was being stored for .png images. This was resulting in an exception `ValueError: invalid literal for int()` being thrown and displayed in the MultimodalQnA UI during follow-up queries.
Related to the [Image_and_Audio_Support_in_MultimodalQnA RFC](https://github.com/opea-project/docs/blob/main/community/rfcs/24-10-02-GenAIExamples-001-Image_and_Audio_Support_in_MultimodalQnA.md)
N/A
N/A
=> Bugfix for follow-up query with a .png image

comps/dataprep/multimodal/redis/langchain/multimodal_utils.py
Fixes a bug in caption generation for videos. The timestamp was unnecessarily multiplied by 1000, which when passed to the MultimodalQnA UI was causing the video clip to not be displayed.
[MultimodalQnA Images & Video Enhancements RFC](https://github.com/opea-project/docs/blob/main/community/rfcs/24-10-02-GenAIExamples-001-Image_and_Audio_Support_in_MultimodalQnA.md)
N/A
N/A
=> Fix units of incorrect caption timestamps

comps/animation/wav2lip/dependency/entrypoint.sh
Add "--no-verbose" flag to wget download commands in entrypoint, so that when docker containers are run, the long download messages won't pop up the console.
`n/a`
`n/a`
Local tests
=> Add "--no-verbose" flag to wget download commands in entrypoint

comps/cores/mega/gateway.py, comps/reranks/tei/reranking_tei.py, comps/retrievers/redis/langchain/retriever_redis.py
When testing DocIndexRetriever with user input k and top_n as ChatCompletionRequest, I identified two errors:
1. retriever redis: previously if input is chat completion request, since the embedding is EmbeddingResponse, it cannot be processed by the vector db, so need to add additional steps to get the embedding vectors out from the EmbeddingResponse.
2. reranker tei: previously input_type is fixed as SearchedDoc, so if the input is ChatCompletionRequest, the microservice will return error 422 unprocessable entity.
As a result of these 2 errors, the DocIndexRetriever fails when user send ChatCompletionRequest.
This PR fixes the issues above. 
List the type of change like below. Please …
=> fix retriever and reranker to process chat completion request

.github/workflows/_comps-workflow.yml, .github/workflows/_run-docker-compose.yml, comps/dataprep/milvus/langchain/prepare_doc_milvus.py, comps/dataprep/milvus/langchain/requirements.txt, comps/dataprep/neo4j/llama_index/extract_graph_neo4j.py, comps/dataprep/neo4j/llama_index/requirements.txt, comps/dataprep/pgvector/langchain/prepare_doc_pgvector.py, comps/dataprep/pgvector/langchain/requirements.txt, comps/dataprep/pinecone/langchain/prepare_doc_pinecone.py, comps/dataprep/pinecone/langchain/requirements.txt, comps/dataprep/qdrant/langchain/prepare_doc_qdrant.py, comps/dataprep/qdrant/langchain/requirements.txt, comps/dataprep/redis/langchain/prepare_doc_redis.py, comps/dataprep/redis/langchain/requirements.txt, comps/dataprep/redis/langchain_ray/prepare_doc_redis_on_ray.py, comps/dataprep/redis/langchain_ray/requirements.txt, comps/dataprep/utils.py, comps/dataprep/vdms/langchain/prepare_doc_vdms.py, comps/dataprep/vdms/langchain/requirements.txt
Fix html content loading problem of dataprep.
Use `AsyncHtmlLoader` of langchain to load and analysis html contents.
Fail to retrieve html contents after uploading html links.
Add `html2text` in `requirements.txt`
Local tested
=> Fix Dataprep Upload Link issue

comps/dataprep/vdms/langchain/requirements.txt, comps/dataprep/vdms/multimodal_langchain/requirements.txt, comps/retrievers/vdms/langchain/requirements.txt
These changes are to fix the error in [Action job #33234707275](https://github.com/opea-project/GenAIComps/actions/runs/11924356081/job/33234707275).  The container crashes and the run complained about the protobuf version.  To fix this, the requirements.txt was modified by pinning the protobuf version, pinned opentelemetry-proto version to avoid any conflict, and provided a minimum vdms version.
Issue #923 
Modified following dependency versions
```
opentelemetry-proto==1.23.0 (pinned to avoid a conflict)
protobuf==4.24.2 (required by vdms)
vdms>=0.0.20
```
Ran the VDMS retriever test locally to verify it runs successfully using the following:
```bash
cd comps/
bash …
```
=> [Bug] Fix VDMS retriever and apply fix to VDMS dataprep

.github/workflows/_get-image-list.yml, .github/workflows/scripts/get_cicd_list.sh
Fix image scan _get-image-list.yml
=> Fix image scan _get-image-list.yml

comps/cores/mega/orchestrator.py
While metrics are OK for small number of requests, when megaservice is handling many (hundreds of) _parallel_ requests, it was reporting clearly (~10%) larger first token latency, than the client receiving the tokens from the megaservice.
Changing timings to be done before token is yielded, means that reported first token latency can be slightly shorter than it actually is. However, testing with ChatQnA shows latencies to be clearly closer to ones seen by the client (within couple of percent) and typically smaller (i.e. logical).
First token latency inaccuracy.    Number being larger than what client sees is obviously incorrect, which throws doubt also on other metrics.
`n/a`
Tested manually with HPA scaled ChatQnA, with benchmark constantly sending (up to 1000) parallel requests.
Doing …
=> Exclude yield/reply time from first token latency metric

comps/embeddings/mosec/langchain/embedding_mosec.py
The performance of asynchronous calling method in Mosec embedding is not better than synchronous calling method, so we will revert to the original synchronous calling method.
synchronous ：
2024-12-04 17:33:09.632 | INFO     | __main__:send_concurrency_requests_zh:167 - Total Concurrency: 256
2024-12-04 17:33:09.632 | INFO     | __main__:send_concurrency_requests_zh:168 - Total Requests: 1280
2024-12-04 17:33:09.632 | INFO     | __main__:send_concurrency_requests_zh:169 - Total Test time: 13.35722827911377
2024-12-04 17:33:09.633 | INFO     | __main__:send_concurrency_requests_zh:180 - AVG total latency is 2.5386883400380613 s
2024-12-04 17:33:09.633 | INFO     | __main__:send_concurrency_requests_zh:181 - P50 total latency is 2.676561951637268 s
2024-12-04 17:33:09.633 | INFO     | …
=> Revert mosec embedding microservice to  to use synchronous interface.

comps/__init__.py, comps/cores/common/__init__.py, comps/cores/common/component.py, tests/cores/common/test_component.py
Add Component base class for code refactoring
`n/a`
None
Local test and pre-CI test.
=> Add Component base class for code refactoring

comps/embeddings/tei/langchain/README.md, comps/embeddings/tei/langchain/embedding_tei.py, tests/embeddings/test_embeddings_tei_langchain.sh
access to embedding wrapper should use /v1/embeddings with {"input", "xxx"}
access to / should use {"inputs": "xxx"} but return are not openai compatible
```python
>>> TEI_EMBEDDING_ENDPOINT
'http://localhost:8090/v1/embeddings'
>>> client = AsyncInferenceClient(model=TEI_EMBEDDING_ENDPOINT, token=HUGGINGFACEHUB_API_TOKEN)
>>> rr=asyncio.run(client.post(json={"input": "Explain the OPEA project"}))
>>> rr
b'{"object":"list","data":[{"object":"embedding","embedding":[-0.0006848863,-0.015310476,-0.037823148,0.011144044,0.042748522,0.0222726,-0.0041277106,0.052072655,-0.011957196,-0.010230217,0.006164461,-0.004530414,-0.07267249,0.036800902,-0.00455364
```
https://github.com/opea-project/GenAIExamples/issues/1263 …
=> Fix wrong endpoint for tei embedding gaudi wrapper

comps/cores/proto/docarray.py, comps/llms/summarization/tgi/langchain/README.md, comps/llms/summarization/tgi/langchain/llm.py, comps/llms/summarization/vllm/langchain/README.md, comps/llms/summarization/vllm/langchain/llm.py, comps/llms/summarization/vllm/langchain/requirements.txt, tests/llms/test_llms_summarization_tgi_langchain.sh
This PR refine previous PR： https://github.com/opea-project/GenAIComps/pull/981 
1. Update refine mode prompt to fix performance problem
2. Add auto mode to automatically select summary_type
=> DocSum Long Context add auto mode

comps/dataprep/pinecone/langchain/README.md, comps/dataprep/pinecone/langchain/pinecone_langchain.yaml, comps/dataprep/pinecone/langchain/prepare_doc_pinecone.py, tests/dataprep/test_dataprep_pinecone_langchain.sh
=> Fix Dataprep pinecone CI issue

comps/llms/text-generation/vllm/langchain/dependency/Dockerfile.intel_gpu
Fix vllm openvino Dockerfile.intel_gpu build issue
Build Dockerfile.intel_gpu will fail because there are dependency conflict when vllm==v0.6.3.post1. Upgrading vllm to v0.6.6.post1 could solve the issue
Fixes [#1141](https://github.com/opea-project/GenAIComps/pull/1141)
https://github.com/opea-project/GenAIComps/pull/1141
- [ √] Bug fix (non-breaking change which fixes an issue)
n/a
=> Fix vllm Openvino Dockerfile.intel_gpu build issue

comps/__init__.py, comps/cores/proto/api_protocol.py, comps/cores/proto/docarray.py, comps/llms/src/doc-summarization/README.md, comps/llms/src/doc-summarization/integrations/common.py, comps/llms/src/doc-summarization/integrations/tgi.py, comps/llms/src/doc-summarization/integrations/vllm.py, comps/llms/src/doc-summarization/opea_docsum_microservice.py, comps/llms/src/faq-generation/README.md, comps/llms/src/faq-generation/integrations/common.py, comps/llms/src/faq-generation/integrations/tgi.py, comps/llms/src/faq-generation/integrations/vllm.py, comps/llms/src/faq-generation/opea_faqgen_microservice.py, comps/llms/src/text-generation/README_native.md, comps/llms/src/text-generation/integrations/native.py, tests/llms/test_llms_doc-summarization_tgi.sh, tests/llms/test_llms_doc-summarization_tgi_on_intel_hpu.sh, tests/llms/test_llms_doc-summarization_vllm_on_intel_hpu.sh, tests/llms/test_llms_faq-generation_tgi.sh, tests/llms/test_llms_faq-generation_tgi_on_intel_hpu.sh, tests/llms/test_llms_faq-generation_vllm_on_intel_hpu.sh, tests/llms/test_llms_text-generation_native_on_intel_hpu.sh
Algin all the inputs to OpenAI API format for FaqGen, DocSum, TextGen-native, now all the services in llm comps should be OpenAI API compatiable
https://github.com/opea-project/GenAIComps/issues/998
no
tests/llm/*.sh
=> Align OpenAI API for FaqGen, DocSum, TextGen-native

comps/cores/mega/orchestrator.py, comps/cores/telemetry/opea_telemetry.py, comps/embeddings/src/opea_embedding_microservice.py, comps/llms/src/text-generation/opea_llm_microservice.py, comps/rerankings/src/opea_reranking_microservice.py, comps/retrievers/src/opea_retrievers_microservice.py
Added open telemetry tracing into OPEA DAG execute path and also couple microservices related to ChatQnA
The purpose is to show tracing timeline for each single request.
depend on https://github.com/opea-project/GenAIExamples/pull/1316
`n/a`.
NA
manually testing
=> add opentelemetry tracing into OPEA DAG and couple microservices code path related to ChatQnA

comps/__init__.py
Disable telemetry by default, if users want to enable telemetry, please pass the env 'ENABLE_OPEA_TELEMETRY' with true.
Many our opea services(e.g. opea/llm-textgen, opea/embedding, opea/reranking, opea/retriever, etc) by default requires a OpenTelemetry trace collector to be in the system. Otherwise, the service will report the [following error](https://gist.github.com/lianhao/6c5e895f3f34fa1ba6b29f3e99432304) every time it process a user request.
`n/a`
None
Local test and CI test.
=> Disable telemetry by default

tests/cores/telemetry/test_telemetry.py
This PR fixes issue with importing opea_telemetry within `test_telemetry.py`
Currently tip of main fails with this:
https://github.com/opea-project/GenAIComps/actions/runs/12836942696/job/35799616804
```
==================================== ERRORS ====================================
___________ ERROR collecting tests/cores/telemetry/test_telemetry.py ___________
ImportError while importing test module '/GenAIComps/tests/cores/telemetry/test_telemetry.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
telemetry/test_telemetry.py:8: in <module>
from comps import opea_telemetry
E   ImportError: cannot import name 'opea_telemetry' from …
```
=> Fix test_telemetry.py import error

.github/workflows/pr-microservice-test.yml
This reverts commit b0abbde6073d5b98c6aa6b51f56ca77802bd2704.
Revert "Fix Workflow Access to id-token for OIDC Auth (#1170)"
This PR revert the change that block the microservice CI. 
=> Revert "Fix Workflow Access to id-token for OIDC Auth (#1170)"

.github/workflows/_comps-workflow.yml, .github/workflows/_run-helm-chart.yml, .github/workflows/manual-comps-test.yml
Fix the issue where CD test files cannot be obtained and add GOOGLE secrets.
=> Fix the issue where CD test files cannot be obtained

comps/dataprep/src/integrations/neo4j_llamaindex.py
Fix stored value for summary into graph DB to store actual text instead of coroutine obj
Added missing await statement to llm.achat call.
- [x ] Bug fix (non-breaking change which fixes an issue)
=> Bug fix neo4j dataprep 

.github/workflows/_comps-workflow.yml, .github/workflows/push-image-build.yml, .github/workflows/scripts/get_test_matrix.sh, comps/third_parties/vllm/src/build_docker_vllm.sh, tests/agent/test_agent_langchain_on_intel_hpu.sh, tests/llms/test_llms_doc-summarization_vllm_on_intel_hpu.sh, tests/llms/test_llms_faq-generation_vllm_on_intel_hpu.sh, tests/llms/test_llms_text-generation_service_vllm_on_intel_hpu.sh
The new triton version 3.2.0 can't work with vllm-gaudi. Freeze the triton version in vllm-gaudi image to 3.1.0.
Issue create for vllm-fork: https://github.com/HabanaAI/vllm-fork/issues/732
=> Freeze the triton version in vllm-gaudi image to 3.1.0

.github/workflows/docker/compose/chathistory-compose.yaml, .github/workflows/manual-docker-publish.yml, comps/chathistory/deployment/docker_compose/compose.yaml, comps/chathistory/src/README.md, tests/chathistory/test_chathistory_mongo.sh
Align image name chathistory-mongo-server with GenAIExamples. 
=> Align image name with GenAIExamples

Dockerfile
Add Docker file for a base image that can be used by GenAIExamples applications.
With a shared base image, CI can do test builds much faster, they take much less space locally and in registry, and images sharing the same base download much faster.
With this, almost all of the 20 application Dockerfiles, e.g. this one:
https://github.com/opea-project/GenAIExamples/blob/main/ChatQnA/Dockerfile
Can be reduced just to:
```
ARG BASE_TAG=latest
FROM opea/comps-base:$BASE_TAG
COPY ./chatqna.py $HOME/chatqna.py
ENTRYPOINT ["python", "chatqna.py"]
```
(For releases, `docker build` command can be given e.g. `--build-arg=BASE_TAG=1.2` option.)
This is first part in fixing image sizes and how much time and disk space is used for them.  There are multiple tickets about the image sizes.
`n/a`
Tested …
=> Add Dockerfile for comps-base image

comps/cores/mega/orchestrator.py
This avoids generating useless token / request histogram metrics for services that use Orchestrator class, but never call its token processing functionality.   Such dummy metrics can confuse telemetry users.
(It also helps in differentiating frontend megaservice metrics from backend megaservice ones, especially when multiple OPEA applications with wrapper microservices run in the same cluster.)
`n/a`.
`n/a`.
Manual testing with latest versions, to verify that:
* services processing tokens, generate token histogram metrics
* ones not processing them, produce only pending requests gauge
=> Create token metrics only when they are available

.github/workflows/_run-helm-chart.yml, comps/guardrails/deployment/kubernetes/README.md
Fix CD test issue.
1. Fix template name in README
2. Fix invalid release name
Test: guardrails,prompt_registry,web_retrievers
Link: https://github.com/opea-project/GenAIComps/actions/runs/13171452809/job/36764974639
Status: guardrails and prompt_registry test passed, web_retrievers test failed due to HF token issues  https://github.com/opea-project/GenAIComps/issues/1264
=> Fix CD test issue.

comps/web_retrievers/deployment/docker_compose/compose.yaml, comps/web_retrievers/src/README.md, comps/web_retrievers/src/requirements.txt
Fix web-retrievers hub client and tei endpoint issue
https://github.com/opea-project/GenAIComps/issues/1268
huggingface-hub==0.27.1
ut
=> Fix web-retrievers hub client and tei endpoint issue

comps/llms/src/text-generation/README.md
In order to change LLM_MODEL_ID properly, we add deepseek model name into validated table and also added required number of gaudi cards into the README.
it is related to this PR.
https://github.com/opea-project/GenAIExamples/pull/1491
[PR#1501](https://github.com/opea-project/GenAIExamples/pull/1501) depends on this change.
`n/a`.
NA
NA
=> Add Deepseek model into validated model table and add required Gaudi cards for LLM microservice 

.github/workflows/_comps-workflow.yml, .github/workflows/push-image-build.yml, comps/llms/src/doc-summarization/requirements.txt, comps/llms/src/faq-generation/requirements.txt, comps/third_parties/vllm/src/build_docker_vllm.sh, tests/agent/test_agent_langchain_on_intel_hpu.sh, tests/guardrails/test_guardrails_hallucination_detection_on_intel_hpu.sh, tests/llms/test_llms_doc-summarization_vllm_on_intel_hpu.sh, tests/llms/test_llms_faq-generation_vllm_on_intel_hpu.sh, tests/llms/test_llms_text-generation_service_vllm_on_intel_hpu.sh
This PR solve two bug:
1. Some bugs exists when using HuggingFaceEndpoint with latest langchain and huggingface_hub version, fix version until fix,    Related issue link: https://github.com/langchain-ai/langchain/issues/29685, https://huggingface.co/mistralai/Mistral-Nemo-Instruct-2407/discussions/42#67a8c255bc29a95bc04e9ec2
2. Remove vllm hpu triton version fix. vllm-fork has fix triton version issue, remove duplicated code https://github.com/HabanaAI/vllm-fork/blob/habana_main/requirements-hpu.txt
`n/a`.
no
=> Fix langchain and huggingface version to avoid bug in FaqGen and DocSum, remove vllm hpu triton version fix

comps/cores/mega/orchestrator.py
- Fix the wrong _instance_id handling in https://github.com/opea-project/GenAIComps/pull/1092
- essential for https://github.com/opea-project/GenAIExamples/pull/1528 UT pass
as above
na
ut
=> Fix metric id issue when initializing multiple Orchestrator instances

.github/workflows/docker/compose/animation-compose.yaml, .github/workflows/push-image-build.yml
Fix Build latest images on push event workflow
https://github.com/opea-project/GenAIExamples/issues/1529
Test: Build animation image on push
Link: https://github.com/opea-project/GenAIComps/actions/runs/13298543830/job/37135625755?pr=1282
https://github.com/opea-project/GenAIComps/actions/runs/13302134288/job/37145347548?pr=1282
Status: passed
=> Fix Build latest images on push event workflow

comps/dataprep/deployment/docker_compose/compose.yaml, comps/dataprep/src/integrations/elasticsearch.py, comps/dataprep/src/integrations/neo4j_llamaindex.py, comps/dataprep/src/integrations/opensearch.py, comps/dataprep/src/integrations/pgvect.py, comps/dataprep/src/integrations/pipecone.py, comps/dataprep/src/integrations/qdrant.py, comps/dataprep/src/integrations/redis.py, comps/dataprep/src/integrations/vdms.py, comps/dataprep/src/opea_dataprep_microservice.py, tests/dataprep/test_dataprep_neo4j_on_intel_hpu.sh
-Fix error handling bug in dataprep/ingest which was returning 200 despite error 
-Renamed "skip_ingestion" argument to "ingest_from_graphDB" for clarity
-Fix parameter handling from opea_dataprep_microservice to neo4j integration. skip_ingestion was undefined causing it to execute the if skip_ingestion condition 
-Ingest_from_graphDB is a feature that skips the file ingestion and creation of graph and jumps directly to clustering and summarization which is part of dataprep (Neo4j dataprep follows Microsoft GraphRAG data preparation steps). Graph extraction is a computationally expensive step users may want to skip after the fist time through. 
- [x ] Bug fix (non-breaking change which fixes an issue)
=> Bug Fix neo4j dataprep ingest error handling and skip_ingestion argument passing

comps/third_parties/vllm/src/build_docker_vllm.sh, tests/llms/test_llms_doc-summarization_vllm.sh, tests/llms/test_llms_faq-generation_vllm.sh
update vLLM CPU to latest stable tag
Default vLLM main branch are in development and changed from time to time. It may be broken sometimes.
https://github.com/opea-project/GenAIExamples/issues/1519
https://github.com/opea-project/GenAIExamples/issues/1532
test local, vLLM works as expected on multiple CPUs.
=> update vLLM CPU to the latest stable version

comps/__init__.py, comps/cores/mega/orchestrator.py, comps/cores/telemetry/opea_telemetry.py, tests/cores/telemetry/test_telemetry.py
- use ENABLE_OPEA_TELEMETRY to control whether to enable open telemetry, default false
- fix the issue that logs always show telemetry connection error with each request when telemetry is disabled
- ban the above error propagation to microservices when telemetry is disabled
https://github.com/opea-project/GenAIExamples/issues/1552
na
ut
=> Fix telemetry connection issue when disabling telemetry

comps/dataprep/src/integrations/milvus.py, comps/dataprep/src/integrations/neo4j_langchain.py
Fix milvus dataprep ingest files failure. This issue is introduced by PR https://github.com/opea-project/GenAIComps/pull/1288
`n/a`
None
Local test and CI test.
=> Fix milvus dataprep ingest files failure

comps/llms/src/text-generation/README_bedrock.md, comps/llms/src/text-generation/integrations/bedrock.py, tests/llms/test_llms_text-generation_bedrock.sh
Enable llm-textgen using Bedrock to accept a string message as well as a list of chat messages.
n/a
n/a
Build and run opea/llm-textgen container. Verify that existing chat format and new string message format both work.
```
curl http://${host_ip}:9009/v1/chat/completions \
-X POST \
-d '{"model": "us.anthropic.claude-3-5-haiku-20241022-v1:0", "messages": [{"role": "user", "content": "What is Deep Learning?"}], "max_tokens":17}' \
-H 'Content-Type: application/json'
```
```
curl http://${host_ip}:9009/v1/chat/completions \
-X POST \
-d '{"model": "us.anthropic.claude-3-5-haiku-20241022-v1:0", "messages": "What is Deep Learning?", "max_tokens":17}' \
-H 'Content-Type: application/json'
```
=> Add support for string message in Bedrock textgen

comps/dataprep/src/README_multimodal.md
This updates the data prep README to fix a couple of issues:
* Fix the name of the docker image name in the build command to match what is used after the [data prep refactor](https://github.com/opea-project/GenAIExamples/pull/1408/files#diff-1d1cfced259dada6f277c25da44cbaea85aa3629b3ce3fb54780c4525a9a3896R147).
* Also in the [data prep refactor](https://github.com/opea-project/GenAIComps/pull/1153/files#diff-d4c7a3a55e0854cbe262901ca8bc6519a662ee5138cea3cf8d5d9f1d27cad870L136-R136), the endpoint was changed from `ingest_with_text` to `data_prep/ingest`, but the heading in was not updated.
N/A
None
None
=> Dataprep Multimodal Redis README fixes

comps/cores/mega/orchestrator.py, comps/cores/mega/orchestrator_with_yaml.py
Revert wrong handling of stream.
There are some reports on ChatQnA and other examples that show the streaming connection was closed before returning any concrete content. In vLLM log it shows the request is aborted without doing any inference and only [DONE] is returned on the frontend. They can be solved by this PR.
https://github.com/opea-project/GenAIExamples/issues/1597
https://github.com/opea-project/GenAIComps/pull/1300#issuecomment-2691013314
na
na
=> Revert wrong handling of stream

comps/cores/proto/api_protocol.py, comps/llms/src/doc-summarization/README.md, comps/llms/src/doc-summarization/integrations/tgi.py, comps/llms/src/doc-summarization/integrations/vllm.py, comps/llms/src/faq-generation/integrations/tgi.py, comps/llms/src/faq-generation/integrations/vllm.py, tests/llms/test_llms_doc-summarization_tgi.sh, tests/llms/test_llms_doc-summarization_tgi_on_intel_hpu.sh, tests/llms/test_llms_doc-summarization_vllm.sh, tests/llms/test_llms_doc-summarization_vllm_on_intel_hpu.sh
Make timeout param configurable, more flexible when deal with longer context.
https://github.com/opea-project/GenAIExamples/issues/1481
no
=> Add timeout param for DocSum and FaqGen to deal with long context

comps/cores/mega/orchestrator.py, tests/cores/mega/test_service_orchestrator_streaming.py
Adds test code for `orchestrator.py` metrics, and fixes for bugs revealed by the test code.
* CI does not verify that orchestrator actually produces any streamed tokens (only that what it produces, is correct)
* First token count was wrong in some situations
* CI was missing tests for orchestrator metrics
`n/a`
* Manual testing with ChatQnA
* New CI test
=> Megaservice / orchestrator metric testing + fixes

comps/third_parties/bridgetower/src/README.md
This PR fixes a documentation bug in the `docker compose up` command in the BridgeTower embedding service README file.
The README was incorrectly saying to use `compose_intel_hpu.yaml` and `compose_intel_cpu.yaml` files, which don't exist in the repo.
None
Tested the README commands for both Xeon and Gaudi.
=> Fix docker compose command in the embedding BridgeTower README

comps/third_parties/bridgetower/src/requirements.txt, comps/third_parties/clip/src/requirements.txt
bridgetower/clip: add missing dependency for aiohttp.
Fixes #1370
=> bridgetower/clip: add missing dependency for aiohttp

comps/dataprep/src/integrations/redis.py, comps/dataprep/src/utils.py
Refine dataprep `redis.py` functions from sync to async to avoid blocking of async health check process.
Initialize embedder once when initializing Dataprep instance, instead of create embeder whenever ingesting data.
Refine utils of `load_pdf` and `save_content_to_local_disk` from sync to async.
https://github.com/opea-project/GenAIComps/issues/1385
None
Local tested
=> Refine Dataprep Redis with Async Issue

comps/dataprep/src/integrations/opensearch.py
Fix the list and delete operations for OpenSearch dataprep.
n/a
n/a
Ingest files using "/v1/dataprep/ingest"
List files using "/v1/dataprep/get"
Delete all files using "/v1/dataprep/delete"
=> Fix file list and index drop for opensearch

comps/retrievers/src/requirements.txt
Add `aiofiles` in requirements.txt of retriever, which is caused by cross-component function call of retriever neo4j.
Fixes #1392
Add `aiofiles`
=> Fix dependency issue in Retriever

comps/cores/mega/orchestrator.py, comps/cores/telemetry/opea_telemetry.py, tests/cores/telemetry/test_telemetry.py
Remove new environment variable and use existed one to disable/enable telemetry feature 
[PR#1168](https://github.com/opea-project/GenAIComps/pull/1168)
might need to pay attention to no proxy setting to make connection to jaeger successful
export no_proxy=chatqna-xeon-ui-server,chatqna-xeon-backend-server,dataprep-redis-service,tei-embedding-service,retriever,tei-reranking-service,tgi-service,vllm-service,jaeger,172.25.116.82,0.0.0.0,localhost
NA
no
manually testing
=> [Telemetry] use existed env variable instead of introducing new one

tests/dataprep/test_dataprep_redis_multimodal.sh
[PR 1362](https://github.com/opea-project/GenAIComps/pull/1362/files#diff-d0e095d7e805e3984c37992788f9b50ff95363841be369f8637212a7e3719970R33) changes the default LVM component from `OPEA_LLAVA_LVM` to `OPEA_VLLM_LVM`. Since the start up of the LVM microservice in the data prep redis multimodal tests were not specifying a `LVM_COMPONENT_NAME`, it's defaulting to vLLM and calls to the LVM endpoint are not working.
An example of the failing test can be seen here: https://github.com/opea-project/GenAIComps/actions/runs/13954018363/job/39085362005?pr=1433
None
Ran test script on Xeon.
=> Fix failing data prep redis multimodal tests that use the LVM

tests/dataprep/test_dataprep_milvus_multimodal.sh
The same issue that I fixed in the redis multimodal tests in PR #1440 is also happening in the Milvus multimodal test. 
Background: [PR 1362](https://github.com/opea-project/GenAIComps/pull/1362/files#diff-d0e095d7e805e3984c37992788f9b50ff95363841be369f8637212a7e3719970R33) changes the default LVM component from `OPEA_LLAVA_LVM` to `OPEA_VLLM_LVM`. Since the start up of the LVM microservice in the data prep Milvus multimodal tests were not specifying a `LVM_COMPONENT_NAME`, it's defaulting to vLLM and calls to the LVM endpoint are not working.
An example of the test failing can be seen [here](https://github.com/opea-project/GenAIComps/actions/runs/13995319401/job/39188942297?pr=1433).
None
This is a test fix.
=> Fix failing data prep milvus multimodal tests that use the LVM

comps/lvms/src/integrations/dependency/llava/README.md
The README file for the LLaVA dependency server is incorrectly using the port/endpoint for the LVM wrapper microservice. Since this README is only starting up and running the LLaVA server, the `curl` commands to `http://localhost:9399/v1/lvm` will fail. 
This PR fixes the `curl` commands to properly reference the LLaVA server using `http://localhost:8399/generate` and updates the request data to match the variable names for that endpoint as well.
Lastly, I updated the `docker run` commands to be detached and give the containers a name to make the instructions easier to follow (when the container is not run detached, it requires opening another terminal).
N/A
N/A
I tested the commands on both Xeon and Gaudi …
=> Fix curl commands in the LLaVA server README

comps/cores/mega/orchestrator.py
Make Orchestrator metrics singleton, so that even if applications instantiate multiple Orchestrators, "megaservice_*" metrics collect data from all of them.
This is intended as proper fix for the https://github.com/opea-project/GenAIComps/pull/1280 workaround.  When only CI tests created multiple Orchestrator instances, changing metric prefix was fine, but now that applications (e.g. DocSum) do that too, that's not the case any more.
(Another option would be to add arguments for passing Orchestrator instance names as metric prefixes, to name and differentiate metrics for each Orchestrator instance. However, that would have needed changes in 4 OPEA projects instead of just this one, and dashboards & benchmarks would then need to hard-code those per-application prefixes.)
Additionally, this …
=> Fix: make Orchestrator metrics singleton

comps/dataprep/src/integrations/elasticsearch.py, comps/dataprep/src/integrations/milvus.py, comps/dataprep/src/integrations/opensearch.py, comps/dataprep/src/integrations/pgvect.py, comps/dataprep/src/integrations/pipecone.py, comps/dataprep/src/integrations/qdrant.py, comps/dataprep/src/integrations/redis.py, comps/dataprep/src/integrations/utils/redis_finance_utils.py, comps/dataprep/src/integrations/vdms.py, comps/retrievers/src/integrations/elasticsearch.py, comps/retrievers/src/integrations/milvus.py, comps/retrievers/src/integrations/opensearch.py, comps/retrievers/src/integrations/pgvector.py, comps/retrievers/src/integrations/pinecone.py, comps/retrievers/src/integrations/redis.py, comps/retrievers/src/integrations/vdms.py, comps/third_parties/pathway/src/requirements.txt, comps/third_parties/pathway/src/vectorstore_pathway.py, requirements.txt
Fix Deprecation warnings in logs service logs
The `HuggingFaceBgeEmbeddings` class deprecated in langchain and there's warning like below:
```bash
/home/user/comps/dataprep/src/integrations/redis.py:210: LangChainDeprecationWarning: The class `HuggingFaceBgeEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. 
An updated version of the class exists in the :class:`~langchain-huggingface package and should be used instead. 
To use it run `pip install -U :class:`~langchain-huggingface` and import as `from :class:`~langchain_huggingface import HuggingFaceEmbeddings``.
```
This PR will update all of the `HuggingFaceBgeEmbeddings` class into `HuggingFaceEmbeddings`.
https://github.com/opea-project/GenAIComps/issues/1434
List the type of change like below. Please delete …
=> Fix Deprecation warnings in logs service logs

README.md, comps/cores/mega/http_service.py, tests/cores/mega/test_microservice.py
For those running Mega/Micro Service, users might need to understand its version for debugging or runtime issues.
Therefore, add a method to get version number at runtime
`n/a`.
NA
Manually test on AWS Xeon instance
=> Return Mega/Micro Service Version number at runtime

comps/retrievers/src/integrations/redis.py
Refactor retriever redis into async to avoid blocking issues with high concurrency.
https://github.com/opea-project/GenAIExamples/issues/1556
None
Local tested
=> Fix Retriever Async Issue

comps/third_parties/nginx/deployment/docker_compose/start-nginx.sh, comps/third_parties/nginx/src/Dockerfile, comps/third_parties/nginx/src/nginx.conf.template, tests/third_parties/test_third_parties_nginx.sh
Change base image from nginx:alpine to nginxinc/nginx-unprivileged
Support parametrization of nginx port
https://github.com/opea-project/GenAIComps/issues/1382
=> Support parametrization of nginx port

tests/agent/test_agent_langchain_on_intel_hpu.sh, tests/guardrails/test_guardrails_guardrails_llamaguard_on_intel_hpu.sh, tests/guardrails/test_guardrails_guardrails_wildguard_on_intel_hpu.sh, tests/guardrails/test_guardrails_hallucination_detection_on_intel_hpu.sh
Use model cache for agent and guardrails docker compose test.
=> Use model cache for agent and guardrails docker compose test.

tests/third_parties/test_third_parties_pathway.sh, tests/third_parties/test_third_parties_vllm_on_amd_gpu.sh, tests/third_parties/test_third_parties_vllm_openvino.sh, tests/third_parties/test_third_parties_vllm_openvino_on_intel_arc.sh
Use model cache for third_parties docker compose test.
=> Use model cache for third_parties docker compose test.

.github/workflows/manual-comps-test.yml, comps/third_parties/tei/deployment/docker_compose/compose.yaml, comps/web_retrievers/deployment/docker_compose/compose.yaml, tests/dataprep/test_dataprep_milvus.sh, tests/dataprep/test_dataprep_neo4j_on_intel_hpu.sh, tests/dataprep/test_dataprep_qdrant.sh, tests/dataprep/test_dataprep_redis.sh, tests/dataprep/test_dataprep_redis_finance_on_intel_hpu.sh, tests/dataprep/test_dataprep_redis_multimodal.sh
Use model cache for dataprep docker compose test. 
Fix web_retrievers typo 
=> Use model cache for dataprep docker compose test.

comps/cores/mega/micro_service.py, comps/cores/mega/orchestrator.py
PR to support remote endpoint interaction for denvr and ibm
none
added access_token for remote endpoint interaction
=> remote endpoint support

comps/finetuning/src/integrations/native.py
Fix fine-tuning Python regex quoting by using raw string type: https://docs.python.org/3/library/re.html#raw-string-notation
CI Python code heck fails in PRs that are not related to fine-tuning without this one-liner fix.
`n/a`
CI
=> Fix fine-tuning Python regex syntax CI/linting error

comps/third_parties/opensearch/deployment/docker_compose/compose.yaml
This PR sets the hard limit for opensearch container as suggested here:
https://opensearch.org/docs/latest/install-and-configure/install-opensearch/index/
- [Y] Bug fix (non-breaking change which fixes an issue)
- [N] New feature (non-breaking change which adds new functionality)
- [N] Breaking change (fix or feature that would break existing design and interface)
- [N] Others (enhancement, documentation, validation, etc.)
N/A
There's a CI test for this.
=> Update nofile's hard limit to 262144 for opensearch

comps/embeddings/deployment/docker_compose/compose.yaml, comps/rerankings/deployment/docker_compose/compose.yaml, comps/rerankings/src/README_ovms.md, comps/rerankings/src/README_tei.md, comps/rerankings/src/README_videoqna.md, comps/third_parties/tei/deployment/docker_compose/compose.yaml
Unify service ports in compose and READMEs for embedding, reranking, and tei components.
n/a
None
CI test
=> Unify service ports in compose and READMEs

comps/agent/src/agent.py, comps/agent/src/integrations/strategy/base_agent.py, comps/agent/src/integrations/strategy/planexec/planner.py, comps/agent/src/integrations/strategy/ragagent/planner.py, comps/agent/src/integrations/strategy/react/planner.py, comps/agent/src/integrations/strategy/sqlagent/planner.py, comps/cores/telemetry/opea_telemetry.py
Enable Telemetry Tracing in major functions of Agent Comp and also add class name + function name as span name for tracing
Some tracing examples are listed below.
1. trace all Agent init functions. understand how many agents are enabled.
2. Trace all major functions calls among Agents. 
3. Trace React Agent (non_streaming-run) 
4. Trace SQL Agent (non_streaming-run) 
This PR depends on https://github.com/opea-project/GenAIExamples/pull/1732
[feature 1542](https://github.com/opea-project/GenAIExamples/issues/1542)
OpenTelemetry
manually test on Gaudi
=> Enable Telemetry Tracing in Agent Comp and also add class name along with func name as span name for tracing

.github/workflows/push-image-build.yml, tests/agent/test_agent_langchain_on_intel_hpu.sh
1. Remove concurrency setting in image build and push workflow, cause the build scope is not the same for each push. 
2. Fix a duplicate container name in agent test.   
=> remove concurrency in image build and push workflow

tests/retrievers/test_retrievers_redis.sh
This PR fixes a test failure that is seen when running the multimodal redis retriever tests. It's using the BridgeTower embedding backend, and not TEI. We need to unset the TEI env var that previous gets set when the redis retriever tests are run.
Without this fix, bringing up the multimodal redis retriever is failing with the following error in the logs:
```
Traceback (most recent call last):
File "/home/user/comps/retrievers/src/opea_retrievers_microservice.py", line 47, in <module>
loader = OpeaComponentLoader(
^^^^^^^^^^^^^^^^^^^^
File "/home/user/comps/cores/common/component.py", line 152, in __init__
self.component = component_class(**kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/user/comps/retrievers/src/integrations/redis.py", line 56, in __init__
self.embeddings = …
```
=> Fix failing multimodal redis retriever tests due to TEI_EMBEDDING_ENDPOINT

.github/workflows/_comps-workflow.yml, .github/workflows/push-image-build.yml, comps/agent/src/README.md, comps/dataprep/src/README_finance.md, comps/third_parties/vllm/src/build_docker_vllm.sh, tests/agent/build_vllm_gaudi.sh, tests/agent/sql_agent_test/test_sql_agent.sh, tests/agent/test_agent_langchain_on_intel_hpu.sh, tests/dataprep/test_dataprep_redis_finance_on_intel_hpu.sh, tests/guardrails/test_guardrails_hallucination_detection_on_intel_hpu.sh, tests/llms/test_llms_doc-summarization_vllm.sh, tests/llms/test_llms_doc-summarization_vllm_on_intel_hpu.sh, tests/llms/test_llms_faq-generation_vllm.sh, tests/llms/test_llms_faq-generation_vllm_on_intel_hpu.sh, tests/llms/test_llms_text-generation_service_vllm_on_intel_hpu.sh
=> Limit vllm and vllm-fork tags

comps/animation/src/integrations/wav2lip.py
Fix #1607 
[List the issue or RFC link this PR is working on. If there is no such link, please mark it as `n/a`.](https://github.com/opea-project/GenAIExamples/issues/1607)
`GenAIExamples/AvatarChatbot/tests/test_compose_on_gaudi.sh`  
`GenAIExamples/AvatarChatbot/tests/test_compose_on_xeon.sh`
=> Fix GenAIExamples #1607 by adding timeout to the wav2lip request

.github/workflows/docker/compose/third_parties-compose.yaml, comps/third_parties/whisper/src/Dockerfile.intel_hpu
1. Fix opea/whisper-gaudi:latest build issue, which is from https://github.com/opea-project/GenAIComps/commit/1e375121fef0dad2bd52cbbfac06781314358aef#diff-ce46d4ab8f2ffd5238f0f4a8bd8140de99e774bbdbf36204cf8d96c08124ff67R27    
2. Fix third party images build issue, which is from https://github.com/opea-project/GenAIComps/pull/1337/files#diff-a388a05aaf0b59761d8006d13343993280e5e0582bf8c3679a9201d8424297a7 
whisper-gaudi issue: https://github.com/opea-project/GenAIExamples/actions/runs/14383337205/job/40332433579#step:6:15928   
third party issue: https://github.com/opea-project/GenAIComps/actions/runs/14397561587/job/40376001446#step:5:109 
Describe …
=> Fix image build issue

comps/dataprep/src/README_redis.md, comps/dataprep/src/integrations/redis.py, comps/dataprep/src/opea_dataprep_microservice.py, comps/dataprep/src/utils.py, tests/dataprep/dataprep_utils.sh, tests/dataprep/test_dataprep_redis.sh
To address the issue mentioned in [issue#1562](https://github.com/opea-project/GenAIComps/issues/1562)
- Index names are removed for dataprep-get
- User can submit a get request for specific index_name
- User can submit a delete request for all items in a specific index_name
- User can submit a delete request for an items in a specific index_name
dataprep/test_dataprep_redis.sh
dataprep/dataprep_utils.sh
=> Remove index_names from files for dataprep-get request 

tests/retrievers/test_retrievers_neo4j_on_intel_hpu.sh
CI environment has OPENAI_KEY so unsetting for test
=> unset OPENAI KEY in retriever neo4j CI test

comps/guardrails/src/bias_detection/README.md, comps/guardrails/src/hallucination_detection/README.md, comps/guardrails/src/hallucination_detection/build_docker_hallucination_microservice.sh
Small typo updates to readmes and additional instruction for ease of use before next release.
n/a
n/a
Manually ran halluc, bias, guardrail and toxicity detection following their readmes and ran their test scripts
=> Minor updates to guardrail comps

comps/cores/proto/api_protocol.py
OpenAI client requires a non null value for StreamOptions.
Before fix, when running `opea/llm-textgen` (using local TGI):
```sh
curl http://localhost:9000/v1/chat/completions \
-X POST \
-d '{"model": "Intel/neural-chat-7b-v3-3", "messages": [{"role": "user", "content": "What is Deep Learning?"}],  "max_tokens":20}' \
-H 'Content-Type: application/json'
```
One would get an error:
```
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: stream_options: invalid type: null, expected struct StreamOptions
```
----
It is explicitly used in here:
https://github.com/opea-project/GenAIComps/blob/402430275b376e1cc4b81042e9eb28d99a96ef2b/comps/llms/src/text-generation/integrations/service.py#L214
Solved using a default factory in pydantic.
`n/a`
List the type …
=> Fix: Default value for StreamOptions

comps/lvms/deployment/docker_compose/compose.yaml
Remove template_llava.jinja in command since its no longer included in default vllm image, and pipeline works fine without it.
`n/a`.
no.
UT.
=> Remove template_llava.jinja in command

comps/dataprep/src/requirements.txt, comps/retrievers/src/requirements.txt
Fix pymilvus==2.5.6, we can remove this version limit after `langchain-milvus` adapt the new release. 
https://github.com/opea-project/GenAIComps/issues/1619
=> fix pymilvus==2.5.6

comps/cores/proto/api_protocol.py
Fix llm inference issue of not passing `stream_options` parameter.
Pydantic will automatically fill a wrong default value for this paremeter, then cause the error:
```bash
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: stream_options: missing field include_usage at line 1 column 273
```
[This PR](https://github.com/opea-project/GenAIComps/pull/1582) partially fixed this issue, but the default value of stream_options should be `Optional[StreamOptions] = Field(default=None)`.
Fixes https://github.com/opea-project/GenAIInfra/issues/1026
None
Local tested
=> Fix LLM StreamOptions Issue

comps/third_parties/vllm/deployment/docker_compose/compose.yaml, comps/third_parties/vllm/src/Dockerfile.intel_gpu
latest openvino is not supported by vllm 
how to fix:
1. set openvino version to 25.0.0 in comps_vllm_openvino_arc dockerfile to resolve bug
2. decrease 'max_model_len' in docker compose file, 8192 is too large
https://github.com/opea-project/GenAIComps/issues/1590
- [ √] Bug fix (non-breaking change which fixes an issue)
n/a
=> fix vllm-openvino-arc openvino version issue

comps/cores/mega/orchestrator.py
Fix request handle timeout issue
[1936](https://github.com/opea-project/GenAIExamples/issues/1936)
None
Local test and CI test
=> Fix request handle timeout issue

comps/dataprep/src/integrations/arangodb.py, comps/retrievers/src/integrations/arangodb.py
Fix embedding issue with ArangoDB due to deprecated HuggingFace API
/home/user/comps/dataprep/src/integrations/arangodb.py:203: LangChainDeprecationWarning: The class `HuggingFaceHubEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-huggingface package and should be used instead. To use it run `pip install -U :class:`~langchain-huggingface` and import as `from :class:`~langchain_huggingface import HuggingFaceEndpointEmbeddings``.
self.embeddings = HuggingFaceHubEmbeddings(
[2025-05-13 15:04:59,871] [    INFO] - Base service - CORS is enabled.
[2025-05-13 15:04:59,872] [    INFO] - Base service - Setting up HTTP server
[2025-05-13 15:04:59,873] [    INFO] - Base service - Uvicorn server setup on port …
=> Fix embedding issue with ArangoDB due to deprecated HuggingFace API

comps/dataprep/src/utils.py
Resolve Hardcoded LVM Endpoint in Dataprep
Get LVM endpoint from environment variables with default value `http://localhost:9399/v1/lvm` 
Fixes https://github.com/opea-project/GenAIComps/issues/1698
None
CI test
=> Resolve Hardcoded LVM Endpoint in Dataprep

comps/text2image/src/requirements.txt
Add missing sentencepiece package for text2image microservice running sd3 model.
When running sd3 model using text2image microservice, the below error was raised:
Traceback (most recent call last):
File "/home/user/comps/text2image/src/opea_text2image_microservice.py", line 59, in <module>
loader = OpeaComponentLoader(
File "/home/user/comps/cores/common/component.py", line 152, in __init__
self.component = component_class(**kwargs)
File "/home/user/comps/text2image/src/integrations/native.py", line 51, in __init__
self.pipe = GaudiStableDiffusion3Pipeline.from_pretrained(
File "/home/user/.local/lib/python3.10/site-packages/optimum/habana/diffusers/pipelines/pipeline_utils.py", line 397, in from_pretrained
model = super().from_pretrained(
File …
=> Add missing sentencepiece package for text2image microservice running sd3 model

comps/finetuning/src/integrations/llm_on_ray/finetune/finetune.py, comps/finetuning/src/integrations/xtune/prepare_xtune.sh, comps/third_parties/llama-vision/src/requirements.txt, comps/third_parties/llama-vision/src/requirements_tp.txt, comps/third_parties/sglang/src/Dockerfile
HF Transformers olders than `v4.50.0` need to be upgraded and that's what this PR is for.
N/A
No new dependencies
Nothing specific except for the CI runs where Dockerfile or scripts have been touched.
=> Upgrade Transformers to minimum v4.50.0 everywhere

comps/dataprep/src/utils.py
Return the same type of data in get_tables_result() to fix issue #1695
Fixes #1695.
=> dataprep: return same type of data in get_tables_result

comps/cores/proto/api_protocol.py, comps/dataprep/src/integrations/arangodb.py, comps/dataprep/src/requirements.txt, comps/retrievers/src/README_arangodb.md, comps/retrievers/src/integrations/arangodb.py, comps/retrievers/src/integrations/config.py, comps/retrievers/src/requirements.txt, tests/dataprep/test_dataprep_arango.sh, tests/retrievers/test_retrievers_arango.sh
Updating `OpeaArangoRetriever` to investigate failure observed here: https://github.com/opea-project/GenAIComps/pull/1746#issuecomment-2923058511
- Also fixing `OpeaArangoDataprep` based on input processing fixes in `OpeaArangoRetriever`
Also introduces `ARANGO_SEARCH_TYPE` as an environment variable to offer selection between Vector & Hybrid search.
N/A
Locks `langchain-arangodb` to `0.0.6`
=> update: OpeaArangoRetriever & OpeaArangoDataprep

comps/retrievers/src/integrations/redis.py
To get perf improvement by replace the keys by dbsize when ingesting large dataset(pubmed_1files.txt,pubmed_10files.txt,pubmed_100files.txt)
Below we could see the throughput got 10.9x speedup, TTFT got 11.4x, with pubmed_100files.txt
Here is a flamegraph shows that the function keys() consumes almost 50% cpu time.
=> improve the performance by replace the keys by dbsize

comps/llms/deployment/docker_compose/compose_doc-summarization.yaml, comps/llms/src/doc-summarization/Dockerfile, comps/llms/src/doc-summarization/README.md, comps/llms/src/doc-summarization/entrypoint.sh, comps/llms/src/doc-summarization/integrations/common.py, comps/llms/src/doc-summarization/requirements-runtime.txt, tests/llms/llm_utils.sh, tests/llms/test_llms_doc-summarization_tgi.sh, tests/llms/test_llms_doc-summarization_vllm.sh
- Replace langserve.serialization with langchain's own serialization functions.
- Add documentation of how to run opea/llm-docsum in air gapped environment.
Partial resolution to issue #264, #1483
=> llm-docsum: Support air gapped environment

Dockerfile.openEuler, comps/dataprep/src/Dockerfile.openEuler, comps/embeddings/src/Dockerfile.openEuler, comps/guardrails/src/guardrails/Dockerfile.openEuler, comps/rerankings/src/Dockerfile.openEuler, comps/retrievers/src/Dockerfile.openEuler, comps/third_parties/nginx/src/Dockerfile.openEuler, tests/dataprep/test_dataprep_redis.sh, tests/embeddings/test_embeddings_tei.sh, tests/guardrails/test_guardrails_bias_detection_distilbias.sh, tests/rerankings/test_rerankings_tei.sh, tests/retrievers/test_retrievers_redis.sh, tests/third_parties/test_third_parties_nginx.sh
Add some Dockerfile(s) for openEuler container image.  
This update enables building and running OPEA components in an openEuler-based environment, improving compatibility and deployment options for users on openEuler systems.
n/a
No new 3rd party runtime dependencies introduced.  
Docker build will utilize openEuler base image and standard package sources.
- Built the openEuler-based Docker image successfully.
- Verified that all OPEA core services start and run correctly in the new container.
- Basic integration tests passed inside the openEuler container.
=> Support for openEuler

.github/workflows/manual-comps-test.yml, .github/workflows/push-base-image-upstream.yml, .github/workflows/push-image-build.yml
Use the same local image registry for gaudi and xeon for the new CICD cluster. 
=> Use one local image registry for gaudi and xeon test

comps/third_parties/opensearch/deployment/docker_compose/compose.yaml
Fix opensearch db fail to start issue.
On new CI machines, error `max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]` occurs when starting opensearch db service.
Enlarge this parameter to fix this issue.
failed CI test: https://github.com/opea-project/GenAIComps/actions/runs/16926181462/job/47962184848?pr=1878#step:5:1864
None
Local tested
=> Fix opensearch db fail to start issue

tests/lvms/test_lvms_predictionguard.sh
Correct failing LVM-Predictionguard service integration CI test by updating image URL
https://github.com/opea-project/GenAIComps/issues/1887
=> fix(test): Correct failing LVM-Predictionguard service integration CI test by updating image URL

comps/dataprep/src/Dockerfile.openEuler
The URL of `libreoffice` is outdated.
https://github.com/opea-project/GenAIExamples/issues/2233
=> Update the URL of  `libreoffice` for DataPrep openEuler
